import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Download, FileText, FileSpreadsheet, FileJson, CalendarIcon, Stethoscope, Share2 } from 'lucide-react';
import { format, subDays } from 'date-fns';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

interface DataExportProps {
  analysisData?: {
    detailedAnalysis?: any;
    patterns?: any[];
    recommendations?: string[];
    dailyData?: any[];
    hourlyData?: any[];
  };
  fileName?: string;
}

export function DataExport({ analysisData, fileName }: DataExportProps) {
  const [open, setOpen] = useState(false);
  const [dateRange, setDateRange] = useState<{ from: Date; to: Date }>({
    from: subDays(new Date(), 14),
    to: new Date()
  });
  const [exportOptions, setExportOptions] = useState({
    includeCharts: true,
    includePatterns: true,
    includeRecommendations: true,
    includeDailyData: true,
    includeRawData: false
  });
  const [exporting, setExporting] = useState(false);

  const exportToPDF = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let yPos = 20;

      // Title
      doc.setFontSize(20);
      doc.setTextColor(88, 28, 135); // Purple
      doc.text('GlucoForge Glucose Report', pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;

      // Date Range
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(
        `Report Period: ${format(dateRange.from, 'MMM d, yyyy')} - ${format(dateRange.to, 'MMM d, yyyy')}`,
        pageWidth / 2, yPos, { align: 'center' }
      );
      yPos += 15;

      // Key Metrics
      if (analysisData?.detailedAnalysis) {
        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text('Key Metrics', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        const metrics = analysisData.detailedAnalysis;
        const metricsText = [
          `Average Glucose: ${metrics.avgGlucose?.toFixed(0) || 'N/A'} mg/dL`,
          `Time in Range (70-180): ${metrics.timeInRange?.toFixed(1) || 'N/A'}%`,
          `Time Below 70: ${metrics.timeBelow70?.toFixed(1) || 'N/A'}%`,
          `Time Above 180: ${metrics.timeAbove180?.toFixed(1) || 'N/A'}%`,
          `GMI (Estimated A1C): ${metrics.gmi?.toFixed(1) || 'N/A'}%`,
          `Coefficient of Variation: ${metrics.cv?.toFixed(1) || 'N/A'}%`
        ];

        metricsText.forEach(text => {
          doc.text(text, 25, yPos);
          yPos += 7;
        });
        yPos += 10;
      }

      // Patterns
      if (exportOptions.includePatterns && analysisData?.patterns?.length) {
        doc.setFontSize(14);
        doc.text('Identified Patterns', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        analysisData.patterns.slice(0, 5).forEach(pattern => {
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
          }
          doc.text(`• ${pattern.title}: ${pattern.description}`, 25, yPos, { maxWidth: pageWidth - 50 });
          yPos += 12;
        });
        yPos += 10;
      }

      // Recommendations
      if (exportOptions.includeRecommendations && analysisData?.recommendations?.length) {
        if (yPos > 240) {
          doc.addPage();
          yPos = 20;
        }
        
        doc.setFontSize(14);
        doc.text('Recommendations', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        analysisData.recommendations.slice(0, 5).forEach(rec => {
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
          }
          doc.text(`• ${rec}`, 25, yPos, { maxWidth: pageWidth - 50 });
          yPos += 10;
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by GlucoForge on ${format(new Date(), 'MMM d, yyyy')}. For discussion with healthcare provider.`,
        pageWidth / 2, 285, { align: 'center' }
      );

      // Save
      doc.save(`glucose-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
      toast.success('PDF report downloaded successfully');
    } catch {
      toast.error('Failed to generate PDF');
    } finally {
      setExporting(false);
      setOpen(false);
    }
  };

  const exportToCSV = () => {
    if (!analysisData?.dailyData?.length) {
      toast.error('No data available to export');
      return;
    }

    const headers = ['Date', 'Average', 'Min', 'Max', 'TIR', 'Readings', 'Low Events', 'High Events'];
    const rows = analysisData.dailyData.map(day => [
      day.date,
      day.avg?.toFixed(0),
      day.min?.toFixed(0),
      day.max?.toFixed(0),
      day.tir?.toFixed(1),
      day.readings,
      day.lowEvents,
      day.highEvents
    ]);

    const csvContent = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `glucose-data-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('CSV data exported successfully');
  };

  const exportToJSON = () => {
    const exportData = {
      exportDate: new Date().toISOString(),
      dateRange: {
        from: dateRange.from.toISOString(),
        to: dateRange.to.toISOString()
      },
      metrics: analysisData?.detailedAnalysis,
      patterns: exportOptions.includePatterns ? analysisData?.patterns : undefined,
      recommendations: exportOptions.includeRecommendations ? analysisData?.recommendations : undefined,
      dailyData: exportOptions.includeDailyData ? analysisData?.dailyData : undefined
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `glucose-data-${format(new Date(), 'yyyy-MM-dd')}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('JSON data exported successfully');
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Download className="h-4 w-4" />
          Export Data
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Download className="h-5 w-5" />
            Export Glucose Data
          </DialogTitle>
          <DialogDescription>
            Download your data for personal use or to share with your healthcare provider.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {/* Date Range */}
          <div className="space-y-2">
            <Label>Date Range</Label>
            <div className="flex gap-2">
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="flex-1 justify-start gap-2">
                    <CalendarIcon className="h-4 w-4" />
                    {format(dateRange.from, 'MMM d')} - {format(dateRange.to, 'MMM d, yyyy')}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="range"
                    selected={{ from: dateRange.from, to: dateRange.to }}
                    onSelect={(range) => {
                      if (range?.from && range?.to) {
                        setDateRange({ from: range.from, to: range.to });
                      }
                    }}
                    numberOfMonths={2}
                  />
                </PopoverContent>
              </Popover>
            </div>
          </div>

          {/* Export Options */}
          <div className="space-y-3">
            <Label>Include in Export</Label>
            <div className="space-y-2">
              {[
                { key: 'includePatterns', label: 'Identified Patterns' },
                { key: 'includeRecommendations', label: 'Recommendations' },
                { key: 'includeDailyData', label: 'Daily Summaries' },
                { key: 'includeRawData', label: 'Raw Readings (CSV/JSON only)' }
              ].map(option => (
                <div key={option.key} className="flex items-center gap-2">
                  <Checkbox
                    id={option.key}
                    checked={exportOptions[option.key as keyof typeof exportOptions]}
                    onCheckedChange={(checked) => 
                      setExportOptions(prev => ({ ...prev, [option.key]: !!checked }))
                    }
                  />
                  <label htmlFor={option.key} className="text-sm">{option.label}</label>
                </div>
              ))}
            </div>
          </div>

          {/* Export Buttons */}
          <div className="grid grid-cols-3 gap-3">
            <Button 
              onClick={exportToPDF} 
              disabled={exporting}
              className="flex-col h-auto py-4 gap-2"
            >
              <FileText className="h-5 w-5" />
              <span className="text-xs">PDF Report</span>
            </Button>
            <Button 
              variant="outline"
              onClick={exportToCSV} 
              className="flex-col h-auto py-4 gap-2"
            >
              <FileSpreadsheet className="h-5 w-5" />
              <span className="text-xs">CSV Data</span>
            </Button>
            <Button 
              variant="outline"
              onClick={exportToJSON} 
              className="flex-col h-auto py-4 gap-2"
            >
              <FileJson className="h-5 w-5" />
              <span className="text-xs">JSON Data</span>
            </Button>
          </div>

          {/* Prepare for Appointment */}
          <Card className="bg-primary/5 border-primary/20">
            <CardContent className="p-4">
              <div className="flex items-start gap-3">
                <Stethoscope className="h-5 w-5 text-primary mt-0.5" />
                <div className="space-y-2">
                  <h4 className="font-medium text-sm">Prepare for Your Appointment</h4>
                  <p className="text-xs text-muted-foreground">
                    The PDF report is formatted for healthcare provider review with key metrics and patterns highlighted.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </DialogContent>
    </Dialog>
  );
}
