import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    console.log('Starting medication seeding...');

    // Comprehensive medication data
    const medications = [
      // ===================== RAPID-ACTING INSULINS =====================
      {
        name: "Humalog",
        generic_name: "Insulin Lispro",
        brand_names: ["Humalog", "Humalog KwikPen"],
        manufacturer: "Eli Lilly",
        category: "Rapid-Acting Insulin",
        subcategory: "Bolus",
        description: "Humalog is a rapid-acting insulin analog used to control blood sugar levels in people with diabetes. It works faster than regular human insulin and is typically taken before meals.",
        mechanism_of_action: "Insulin lispro is a recombinant human insulin analog that differs from human insulin by the reversal of amino acids at positions 28 and 29 of the B chain. This modification allows for faster absorption and onset of action.",
        onset_time: "15-30 minutes",
        peak_time: "1-2 hours",
        duration: "3-5 hours",
        typical_dosing: "Inject 15 minutes before or immediately after a meal. Dose is individualized based on blood glucose monitoring.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "1996-06-14",
        last_updated_date: "2023-09-15",
        avg_price: 274.70,
        medicare_price: 35.00,
        insurance_coverage_notes: "Covered by most insurance plans. Generic versions available at lower cost.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain", "Lipodystrophy", "Allergic reactions"],
        serious_warnings: ["Severe hypoglycemia can cause seizures, unconsciousness, or death", "Never share insulin pens between patients", "Hypokalemia may occur"],
        contraindications: ["Hypersensitivity to insulin lispro", "During episodes of hypoglycemia"],
        storage_requirements: "Refrigerate unopened vials at 36°F to 46°F. Once opened, can be kept at room temperature for up to 28 days.",
        key_features: ["Fast onset of action", "Can be injected immediately before meals", "Available in pen and vial forms", "Biosimilars available"],
        pros: ["Works quickly", "Flexible meal timing", "Well-established safety profile", "Multiple delivery options"],
        cons: ["Requires refrigeration", "Can cause hypoglycemia", "Multiple daily injections needed", "Cost can be high without insurance"],
        future_developments: "Lilly continues to develop faster-acting formulations and connected pen devices for improved dosing accuracy.",
        clinical_notes: "First rapid-acting insulin analog approved. Considered gold standard for mealtime insulin coverage.",
        usage_statistics: { popularity_rank: 2, monthly_prescriptions: 2100000, user_satisfaction: 4.2 },
        fda_status: "Approved",
        rating_avg: 4.2,
        review_count: 1847,
        popularity_rank: 2,
        featured: true
      },
      {
        name: "Novolog",
        generic_name: "Insulin Aspart",
        brand_names: ["Novolog", "NovoLog FlexPen", "NovoLog FlexTouch"],
        manufacturer: "Novo Nordisk",
        category: "Rapid-Acting Insulin",
        subcategory: "Bolus",
        description: "Novolog is a rapid-acting insulin used to improve glycemic control in adults and children with diabetes mellitus. It has a faster onset and shorter duration of action than regular human insulin.",
        mechanism_of_action: "Insulin aspart is a recombinant human insulin analog where the amino acid proline at position B28 is substituted by aspartic acid. This reduces the tendency to form hexamers, allowing faster absorption.",
        onset_time: "10-20 minutes",
        peak_time: "1-3 hours",
        duration: "3-5 hours",
        typical_dosing: "Inject 5-10 minutes before starting a meal. Dose individualized based on metabolic needs and blood glucose monitoring.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2000-06-07",
        last_updated_date: "2023-11-01",
        avg_price: 289.36,
        medicare_price: 35.00,
        insurance_coverage_notes: "Widely covered. Authorized generic available.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Lipodystrophy", "Weight gain", "Edema"],
        serious_warnings: ["Risk of severe hypoglycemia", "Hypokalemia", "Fluid retention with thiazolidinediones"],
        contraindications: ["Hypersensitivity to insulin aspart", "During hypoglycemic episodes"],
        storage_requirements: "Refrigerate at 36°F to 46°F. In-use pens/vials can be kept at room temperature for up to 28 days.",
        key_features: ["Fastest onset among traditional rapid-acting insulins", "Compatible with insulin pumps", "FlexTouch pen is easy to use"],
        pros: ["Very fast acting", "Pump compatible", "Easy-to-use pen design", "Well-tolerated"],
        cons: ["Expensive without insurance", "Requires careful timing", "Needs refrigeration"],
        future_developments: "Novo Nordisk is developing smart pen integration and glucose-responsive insulin formulations.",
        clinical_notes: "Widely used in insulin pumps due to stability and fast action. Popular choice for carb counting.",
        usage_statistics: { popularity_rank: 1, monthly_prescriptions: 2500000, user_satisfaction: 4.3 },
        fda_status: "Approved",
        rating_avg: 4.3,
        review_count: 2156,
        popularity_rank: 1,
        featured: true
      },
      {
        name: "Apidra",
        generic_name: "Insulin Glulisine",
        brand_names: ["Apidra", "Apidra SoloStar"],
        manufacturer: "Sanofi",
        category: "Rapid-Acting Insulin",
        subcategory: "Bolus",
        description: "Apidra is a rapid-acting human insulin analog used to treat diabetes mellitus. It provides quick blood sugar control after meals.",
        mechanism_of_action: "Insulin glulisine differs from human insulin by substitution of asparagine for lysine at position B3 and lysine for glutamic acid at position B29, enabling rapid absorption.",
        onset_time: "15-30 minutes",
        peak_time: "1 hour",
        duration: "3-4 hours",
        typical_dosing: "Inject within 15 minutes before or 20 minutes after starting a meal.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2004-04-16",
        last_updated_date: "2022-08-20",
        avg_price: 282.45,
        medicare_price: 35.00,
        insurance_coverage_notes: "Covered by most plans but may require prior authorization.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Allergic reactions", "Weight gain"],
        serious_warnings: ["Severe hypoglycemia risk", "Do not mix with other insulins except NPH"],
        contraindications: ["Hypersensitivity to insulin glulisine", "Hypoglycemia"],
        storage_requirements: "Refrigerate unused. Room temperature for up to 28 days once opened.",
        key_features: ["Shortest duration of rapid-acting insulins", "Good for those prone to late hypoglycemia", "Zinc-free formulation"],
        pros: ["Shortest duration reduces late hypos", "Can dose after meals", "Zinc-free"],
        cons: ["Less commonly prescribed", "May need more frequent dosing", "Limited pen options"],
        future_developments: "Sanofi focusing on biosimilar competition and connected care solutions.",
        clinical_notes: "Preferred by some patients who experience late post-meal hypoglycemia with other rapid-acting insulins.",
        usage_statistics: { popularity_rank: 6, monthly_prescriptions: 450000, user_satisfaction: 4.0 },
        fda_status: "Approved",
        rating_avg: 4.0,
        review_count: 523,
        popularity_rank: 6,
        featured: false
      },
      {
        name: "Fiasp",
        generic_name: "Insulin Aspart (faster-acting)",
        brand_names: ["Fiasp", "Fiasp FlexTouch", "Fiasp PenFill"],
        manufacturer: "Novo Nordisk",
        category: "Rapid-Acting Insulin",
        subcategory: "Ultra-Rapid Bolus",
        description: "Fiasp is an ultra-rapid-acting insulin aspart formulation with added niacinamide for faster initial absorption. It more closely mimics natural mealtime insulin release.",
        mechanism_of_action: "Contains insulin aspart with niacinamide (vitamin B3) which increases local blood flow and L-arginine as a stabilizer, resulting in faster absorption.",
        onset_time: "2.5-5 minutes",
        peak_time: "1-1.5 hours",
        duration: "3-5 hours",
        typical_dosing: "Inject at the start of a meal or within 20 minutes after starting a meal.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2017-09-29",
        last_updated_date: "2023-06-15",
        avg_price: 546.72,
        medicare_price: 35.00,
        insurance_coverage_notes: "May require prior authorization. Step therapy may apply.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Lipodystrophy", "Allergic reactions"],
        serious_warnings: ["Faster onset may increase hypoglycemia risk if meal is delayed", "Monitor closely when switching from other insulins"],
        contraindications: ["Hypersensitivity to insulin aspart", "During hypoglycemia"],
        storage_requirements: "Refrigerate at 36°F to 46°F. In-use up to 28 days at room temperature.",
        key_features: ["Fastest-acting insulin available", "Can dose at start of meal or after", "Better postprandial control"],
        pros: ["Ultra-fast onset", "Better post-meal spikes control", "Flexible dosing timing", "Good for high-carb meals"],
        cons: ["Higher cost", "May require dose adjustments", "More hypo risk if meal delayed"],
        future_developments: "Novo Nordisk exploring pump formulations and closed-loop system optimization.",
        clinical_notes: "Especially beneficial for patients struggling with post-meal glucose spikes. Popular in hybrid closed-loop systems.",
        usage_statistics: { popularity_rank: 4, monthly_prescriptions: 890000, user_satisfaction: 4.4 },
        fda_status: "Approved",
        rating_avg: 4.4,
        review_count: 987,
        popularity_rank: 4,
        featured: true
      },
      {
        name: "Lyumjev",
        generic_name: "Insulin Lispro-aabc",
        brand_names: ["Lyumjev", "Lyumjev KwikPen", "Lyumjev Tempo Pen"],
        manufacturer: "Eli Lilly",
        category: "Rapid-Acting Insulin",
        subcategory: "Ultra-Rapid Bolus",
        description: "Lyumjev is an ultra-rapid-acting insulin lispro formulation with treprostinil and citrate for faster absorption. Designed to more closely match the body's natural insulin response to meals.",
        mechanism_of_action: "Contains insulin lispro with treprostinil (a vasodilator) and citrate to increase local vascular permeability and accelerate absorption.",
        onset_time: "5 minutes",
        peak_time: "1 hour",
        duration: "4-5 hours",
        typical_dosing: "Inject at the beginning of a meal or within 20 minutes after starting a meal.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2020-06-12",
        last_updated_date: "2023-10-01",
        avg_price: 530.88,
        medicare_price: 35.00,
        insurance_coverage_notes: "Prior authorization often required. Some plans prefer Fiasp.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Lipodystrophy", "Pruritus"],
        serious_warnings: ["Fast onset requires careful meal timing", "May cause more injection site reactions than standard lispro"],
        contraindications: ["Hypersensitivity to insulin lispro", "During hypoglycemia"],
        storage_requirements: "Refrigerate before first use. Room temperature up to 28 days after opening.",
        key_features: ["Ultra-fast onset similar to Fiasp", "Better post-meal control", "Compatible with some pumps"],
        pros: ["Very rapid action", "Reduces post-meal spikes", "Lilly's extensive support network"],
        cons: ["More injection site reactions reported", "Expensive", "Newer with less long-term data"],
        future_developments: "Lilly developing automated insulin delivery partnerships and connected pen technology.",
        clinical_notes: "Alternative to Fiasp for ultra-rapid mealtime coverage. Some patients report more stinging at injection site.",
        usage_statistics: { popularity_rank: 7, monthly_prescriptions: 340000, user_satisfaction: 4.2 },
        fda_status: "Approved",
        rating_avg: 4.2,
        review_count: 445,
        popularity_rank: 7,
        featured: false
      },
      {
        name: "Admelog",
        generic_name: "Insulin Lispro (biosimilar)",
        brand_names: ["Admelog", "Admelog SoloStar"],
        manufacturer: "Sanofi",
        category: "Rapid-Acting Insulin",
        subcategory: "Bolus",
        description: "Admelog is a biosimilar to Humalog, offering the same rapid-acting insulin lispro at a lower cost.",
        mechanism_of_action: "Identical to reference product insulin lispro. Rapid absorption due to amino acid modifications at B28 and B29.",
        onset_time: "15-30 minutes",
        peak_time: "1-2 hours",
        duration: "3-5 hours",
        typical_dosing: "Inject 15 minutes before or immediately after meals.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2017-12-11",
        last_updated_date: "2023-03-20",
        avg_price: 155.32,
        medicare_price: 35.00,
        insurance_coverage_notes: "Often preferred by insurance due to lower cost. Interchangeable with Humalog.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain", "Lipodystrophy"],
        serious_warnings: ["Same warnings as Humalog", "Severe hypoglycemia risk"],
        contraindications: ["Hypersensitivity to insulin lispro", "Hypoglycemia"],
        storage_requirements: "Same as Humalog. Refrigerate, room temperature 28 days.",
        key_features: ["Lower cost biosimilar", "FDA-approved interchangeable", "Same efficacy as Humalog"],
        pros: ["Significantly cheaper", "Same effectiveness", "Widely available"],
        cons: ["Less brand recognition", "Some patients report slight differences"],
        future_developments: "Continued pricing competition in biosimilar insulin market.",
        clinical_notes: "Excellent cost-effective alternative to Humalog with identical clinical performance.",
        usage_statistics: { popularity_rank: 5, monthly_prescriptions: 670000, user_satisfaction: 4.1 },
        fda_status: "Approved",
        rating_avg: 4.1,
        review_count: 612,
        popularity_rank: 5,
        featured: false
      },

      // ===================== LONG-ACTING INSULINS =====================
      {
        name: "Lantus",
        generic_name: "Insulin Glargine",
        brand_names: ["Lantus", "Lantus SoloStar"],
        manufacturer: "Sanofi",
        category: "Long-Acting Insulin",
        subcategory: "Basal",
        description: "Lantus is a long-acting insulin analog providing 24-hour basal coverage. It forms microprecipitates under the skin for slow, steady release.",
        mechanism_of_action: "Modified human insulin with glycine at A21 and two arginines at B-chain terminus. Forms microprecipitates at physiological pH, creating a depot for gradual release.",
        onset_time: "1-2 hours",
        peak_time: "No pronounced peak",
        duration: "Up to 24 hours",
        typical_dosing: "Once daily at the same time each day. Starting dose typically 10 units or 0.1-0.2 units/kg.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2000-04-20",
        last_updated_date: "2023-08-01",
        avg_price: 283.56,
        medicare_price: 35.00,
        insurance_coverage_notes: "Widely covered. Biosimilars available at lower cost.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain", "Lipodystrophy", "Edema"],
        serious_warnings: ["Do not dilute or mix with other insulins", "Monitor for hypoglycemia, especially when adjusting dose"],
        contraindications: ["Hypersensitivity to insulin glargine", "During hypoglycemia"],
        storage_requirements: "Refrigerate before first use. Room temperature up to 28 days after opening.",
        key_features: ["True 24-hour coverage", "No pronounced peak", "Once-daily dosing", "Extensive clinical data"],
        pros: ["Predictable action", "Once daily", "Well-studied", "Reduced nocturnal hypos"],
        cons: ["Cannot be mixed", "Slightly acidic causing stinging", "Weight gain possible"],
        future_developments: "Focus on biosimilar competition and digital health integration.",
        clinical_notes: "Gold standard basal insulin. Revolutionized diabetes management with true once-daily dosing.",
        usage_statistics: { popularity_rank: 3, monthly_prescriptions: 1800000, user_satisfaction: 4.3 },
        fda_status: "Approved",
        rating_avg: 4.3,
        review_count: 2534,
        popularity_rank: 3,
        featured: true
      },
      {
        name: "Basaglar",
        generic_name: "Insulin Glargine (biosimilar)",
        brand_names: ["Basaglar", "Basaglar KwikPen"],
        manufacturer: "Eli Lilly",
        category: "Long-Acting Insulin",
        subcategory: "Basal",
        description: "Basaglar is a biosimilar to Lantus, offering the same long-acting basal coverage at a reduced price.",
        mechanism_of_action: "Same as Lantus. Forms microprecipitates for slow, steady insulin release.",
        onset_time: "1-2 hours",
        peak_time: "No pronounced peak",
        duration: "Up to 24 hours",
        typical_dosing: "Once daily at consistent time. Individualize dose based on needs.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2015-12-16",
        last_updated_date: "2023-05-10",
        avg_price: 199.52,
        medicare_price: 35.00,
        insurance_coverage_notes: "Often preferred tier on formularies due to cost savings.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
        serious_warnings: ["Same as Lantus", "Do not mix with other insulins"],
        contraindications: ["Hypersensitivity to insulin glargine", "Hypoglycemia"],
        storage_requirements: "Same as Lantus storage requirements.",
        key_features: ["Lower cost than Lantus", "Same efficacy", "KwikPen delivery system"],
        pros: ["Cost savings", "Proven efficacy", "Good pen design"],
        cons: ["Not interchangeable everywhere", "Some insurance confusion"],
        future_developments: "Continued market expansion and pricing competition.",
        clinical_notes: "First biosimilar insulin approved in US. Excellent clinical outcomes matching Lantus.",
        usage_statistics: { popularity_rank: 8, monthly_prescriptions: 780000, user_satisfaction: 4.2 },
        fda_status: "Approved",
        rating_avg: 4.2,
        review_count: 876,
        popularity_rank: 8,
        featured: false
      },
      {
        name: "Toujeo",
        generic_name: "Insulin Glargine U-300",
        brand_names: ["Toujeo", "Toujeo SoloStar", "Toujeo Max SoloStar"],
        manufacturer: "Sanofi",
        category: "Long-Acting Insulin",
        subcategory: "Basal (Concentrated)",
        description: "Toujeo is a concentrated long-acting insulin providing extended coverage beyond 24 hours with a flatter profile and potentially less hypoglycemia risk.",
        mechanism_of_action: "Three times more concentrated than Lantus, forming a smaller subcutaneous depot that releases more slowly and evenly.",
        onset_time: "6 hours",
        peak_time: "No peak",
        duration: "Up to 36 hours",
        typical_dosing: "Once daily. Note: NOT interchangeable unit-for-unit with other insulins due to concentration.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2015-02-25",
        last_updated_date: "2023-09-20",
        avg_price: 338.16,
        medicare_price: 35.00,
        insurance_coverage_notes: "May require prior authorization. Often tier 3.",
        common_side_effects: ["Hypoglycemia (less than Lantus)", "Injection site reactions", "Weight gain"],
        serious_warnings: ["Not interchangeable unit-for-unit with other glargine products", "Higher dose needed when switching from Lantus"],
        contraindications: ["Hypersensitivity to insulin glargine", "Hypoglycemia"],
        storage_requirements: "Refrigerate before use. 56 days at room temperature after first use.",
        key_features: ["Longer duration", "Flatter profile", "Less hypoglycemia", "Max pen holds 900 units"],
        pros: ["Extended coverage", "Reduced hypo risk", "Flexible timing", "Good for high-dose patients"],
        cons: ["Slower onset", "Dose adjustment when switching", "Higher cost"],
        future_developments: "Expanding Max SoloStar for patients requiring very high doses.",
        clinical_notes: "Preferred for patients with nocturnal hypoglycemia on Lantus or those needing high doses.",
        usage_statistics: { popularity_rank: 10, monthly_prescriptions: 540000, user_satisfaction: 4.4 },
        fda_status: "Approved",
        rating_avg: 4.4,
        review_count: 634,
        popularity_rank: 10,
        featured: false
      },
      {
        name: "Levemir",
        generic_name: "Insulin Detemir",
        brand_names: ["Levemir", "Levemir FlexTouch"],
        manufacturer: "Novo Nordisk",
        category: "Long-Acting Insulin",
        subcategory: "Basal",
        description: "Levemir is a long-acting insulin analog with albumin binding for prolonged action. May be given once or twice daily.",
        mechanism_of_action: "Fatty acid chain attached at B29 allows reversible albumin binding in subcutaneous tissue and bloodstream, providing slow, prolonged release.",
        onset_time: "1-2 hours",
        peak_time: "6-8 hours (mild)",
        duration: "Up to 24 hours",
        typical_dosing: "Once or twice daily based on individual needs. Often twice daily for tighter control.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2005-06-16",
        last_updated_date: "2022-11-15",
        avg_price: 323.52,
        medicare_price: 35.00,
        insurance_coverage_notes: "Covered by most plans but losing market share to newer options.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain (less than NPH)"],
        serious_warnings: ["Do not mix with other insulins", "Dose adjustment may be needed when switching"],
        contraindications: ["Hypersensitivity to insulin detemir", "Hypoglycemia"],
        storage_requirements: "Refrigerate before use. 42 days at room temperature once opened.",
        key_features: ["Albumin binding mechanism", "Weight-neutral for some patients", "Clear solution"],
        pros: ["Less weight gain than NPH", "Flexible dosing", "Good for pregnancy"],
        cons: ["Often needs twice daily dosing", "Mild peak exists", "Being phased out"],
        future_developments: "Being replaced by Tresiba in Novo's portfolio.",
        clinical_notes: "Popular in pregnancy due to safety data. Being superseded by Tresiba for most indications.",
        usage_statistics: { popularity_rank: 12, monthly_prescriptions: 380000, user_satisfaction: 4.1 },
        fda_status: "Approved",
        rating_avg: 4.1,
        review_count: 567,
        popularity_rank: 12,
        featured: false
      },
      {
        name: "Tresiba",
        generic_name: "Insulin Degludec",
        brand_names: ["Tresiba", "Tresiba FlexTouch"],
        manufacturer: "Novo Nordisk",
        category: "Long-Acting Insulin",
        subcategory: "Ultra-Long Basal",
        description: "Tresiba is an ultra-long-acting basal insulin with duration exceeding 42 hours, offering the most flexible dosing window of any basal insulin.",
        mechanism_of_action: "Forms multi-hexamer chains after injection, creating a depot that slowly releases monomers. Unique structure provides ultra-long, flat action profile.",
        onset_time: "1 hour",
        peak_time: "No peak",
        duration: "42+ hours",
        typical_dosing: "Once daily with flexible timing (8-40 hours between doses acceptable).",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2015-09-25",
        last_updated_date: "2023-12-01",
        avg_price: 393.12,
        medicare_price: 35.00,
        insurance_coverage_notes: "May require prior authorization but increasingly covered.",
        common_side_effects: ["Hypoglycemia (less frequent)", "Injection site reactions", "Weight gain"],
        serious_warnings: ["Do not use in insulin pumps", "Monitor during illness"],
        contraindications: ["Hypersensitivity to insulin degludec", "Hypoglycemia"],
        storage_requirements: "Refrigerate before use. 56 days at room temperature once opened.",
        key_features: ["Longest duration", "Most flexible timing", "Lowest hypoglycemia risk", "Flat profile"],
        pros: ["Flexible dosing window", "Very stable levels", "Reduced severe hypos", "Once-daily"],
        cons: ["Higher cost", "Slow to steady-state (3-4 days)", "Can't use in pumps"],
        future_developments: "Combined with liraglutide in Xultophy. Studies in pregnancy ongoing.",
        clinical_notes: "Preferred for patients with hypoglycemia unawareness or variable schedules. Best basal insulin for stability.",
        usage_statistics: { popularity_rank: 9, monthly_prescriptions: 620000, user_satisfaction: 4.6 },
        fda_status: "Approved",
        rating_avg: 4.6,
        review_count: 1123,
        popularity_rank: 9,
        featured: true
      },
      {
        name: "Semglee",
        generic_name: "Insulin Glargine-yfgn (biosimilar)",
        brand_names: ["Semglee"],
        manufacturer: "Mylan/Viatris",
        category: "Long-Acting Insulin",
        subcategory: "Basal",
        description: "Semglee is the first interchangeable biosimilar insulin in the US, equivalent to Lantus at a lower cost.",
        mechanism_of_action: "Identical to Lantus insulin glargine. Forms microprecipitates for steady release.",
        onset_time: "1-2 hours",
        peak_time: "No pronounced peak",
        duration: "Up to 24 hours",
        typical_dosing: "Once daily at the same time each day.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2021-07-28",
        last_updated_date: "2023-07-15",
        avg_price: 147.98,
        medicare_price: 35.00,
        insurance_coverage_notes: "Often tier 1 on formularies. Significant savings opportunity.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
        serious_warnings: ["Same as Lantus"],
        contraindications: ["Hypersensitivity to insulin glargine", "Hypoglycemia"],
        storage_requirements: "Same as Lantus.",
        key_features: ["First interchangeable biosimilar", "Significant cost savings", "Pharmacist can substitute"],
        pros: ["Lowest cost glargine", "True interchangeability", "Same efficacy"],
        cons: ["Newer to market", "Some pharmacies may not stock"],
        future_developments: "Expected to gain significant market share as awareness grows.",
        clinical_notes: "Excellent option for cost-conscious patients. Can be substituted by pharmacist without new prescription.",
        usage_statistics: { popularity_rank: 11, monthly_prescriptions: 420000, user_satisfaction: 4.2 },
        fda_status: "Approved",
        rating_avg: 4.2,
        review_count: 312,
        popularity_rank: 11,
        featured: false
      },

      // ===================== INHALED INSULIN =====================
      {
        name: "Afrezza",
        generic_name: "Insulin Human (inhalation powder)",
        brand_names: ["Afrezza"],
        manufacturer: "MannKind Corporation",
        category: "Inhaled Insulin",
        subcategory: "Ultra-Rapid Bolus",
        description: "Afrezza is an inhaled rapid-acting insulin delivered as a powder to the lungs. It offers needle-free mealtime insulin with ultra-fast onset.",
        mechanism_of_action: "Technosphere insulin microparticles deliver regular human insulin directly to lung tissue for rapid systemic absorption.",
        onset_time: "12-15 minutes",
        peak_time: "35-55 minutes",
        duration: "1.5-3 hours",
        typical_dosing: "Inhale at beginning of meal. Dose based on 4-unit, 8-unit, or 12-unit cartridges.",
        administration_route: "Oral inhalation",
        fda_approval_date: "2014-06-27",
        last_updated_date: "2023-10-15",
        avg_price: 563.04,
        medicare_price: 35.00,
        insurance_coverage_notes: "Coverage varies. Often requires prior authorization and pulmonary testing.",
        common_side_effects: ["Hypoglycemia", "Cough", "Throat pain/irritation", "Headache"],
        serious_warnings: ["CONTRAINDICATED in chronic lung disease (asthma, COPD)", "Acute bronchospasm reported", "Lung function testing required", "Black box warning for bronchospasm"],
        contraindications: ["Chronic lung disease (asthma, COPD)", "Active smoking", "Hypersensitivity"],
        storage_requirements: "Refrigerate sealed. Room temperature up to 10 days for opened foil packages.",
        key_features: ["Needle-free", "Ultra-fast onset", "Short duration reduces hypo risk", "Discreet"],
        pros: ["No injections", "Fastest peak action", "Short duration good for snacks", "Discreet use"],
        cons: ["Requires lung testing", "Not for lung disease", "Learning curve", "Dosing increments limited"],
        future_developments: "MannKind exploring additional cartridge sizes and expanded indications.",
        clinical_notes: "Unique option for needle-phobic patients without lung disease. Short duration great for small carb intake.",
        usage_statistics: { popularity_rank: 15, monthly_prescriptions: 45000, user_satisfaction: 4.0 },
        fda_status: "Approved",
        rating_avg: 4.0,
        review_count: 234,
        popularity_rank: 15,
        featured: false
      },

      // ===================== INTERMEDIATE-ACTING INSULINS =====================
      {
        name: "Humulin N",
        generic_name: "NPH Insulin Human",
        brand_names: ["Humulin N", "Humulin N KwikPen"],
        manufacturer: "Eli Lilly",
        category: "Intermediate-Acting Insulin",
        subcategory: "NPH",
        description: "Humulin N is an intermediate-acting human insulin suspension used for basal coverage, often given twice daily.",
        mechanism_of_action: "Protamine and zinc suspension creates crystals that slowly dissolve, providing intermediate duration of action.",
        onset_time: "1-3 hours",
        peak_time: "4-8 hours",
        duration: "14-24 hours",
        typical_dosing: "Usually twice daily. Must be rolled gently to resuspend before each use.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "1982-10-29",
        last_updated_date: "2022-06-01",
        avg_price: 148.70,
        medicare_price: 35.00,
        insurance_coverage_notes: "Well-covered, often preferred due to low cost.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
        serious_warnings: ["Must resuspend before use", "Peak action increases hypo risk at peak time"],
        contraindications: ["Hypersensitivity to NPH insulin", "Hypoglycemia"],
        storage_requirements: "Refrigerate. Room temperature 28 days. Must remain cloudy when resuspended.",
        key_features: ["Lower cost", "Can mix with rapid-acting", "Established track record"],
        pros: ["Affordable", "Long track record", "Can be mixed", "OTC in some states"],
        cons: ["Peak causes hypos", "Twice daily usually", "Must be mixed properly"],
        future_developments: "Being replaced by basal analogs but remains important for cost-conscious care.",
        clinical_notes: "Still valuable for cost-constrained patients. Peak action timing is critical for meal planning.",
        usage_statistics: { popularity_rank: 13, monthly_prescriptions: 320000, user_satisfaction: 3.8 },
        fda_status: "Approved",
        rating_avg: 3.8,
        review_count: 445,
        popularity_rank: 13,
        featured: false
      },
      {
        name: "Novolin N",
        generic_name: "NPH Insulin Human (Novo)",
        brand_names: ["Novolin N", "Novolin N FlexPen"],
        manufacturer: "Novo Nordisk",
        category: "Intermediate-Acting Insulin",
        subcategory: "NPH",
        description: "Novolin N is Novo Nordisk's NPH insulin, providing intermediate-acting basal coverage.",
        mechanism_of_action: "Same as Humulin N. Protamine zinc suspension for prolonged action.",
        onset_time: "1-3 hours",
        peak_time: "4-8 hours",
        duration: "14-24 hours",
        typical_dosing: "Usually twice daily. Resuspend before each injection.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "1991-07-30",
        last_updated_date: "2022-05-15",
        avg_price: 144.80,
        medicare_price: 35.00,
        insurance_coverage_notes: "Good coverage, available OTC at Walmart at lower price.",
        common_side_effects: ["Hypoglycemia", "Injection site reactions", "Weight gain"],
        serious_warnings: ["Same as Humulin N"],
        contraindications: ["Hypersensitivity to NPH insulin", "Hypoglycemia"],
        storage_requirements: "Same as Humulin N.",
        key_features: ["Available OTC at Walmart", "Lower cost option", "Mixable"],
        pros: ["Very affordable", "Widely available", "OTC access"],
        cons: ["Same peak issues as all NPH", "Less predictable", "Twice daily"],
        future_developments: "ReliOn branding at Walmart continues to expand access.",
        clinical_notes: "Important access option. ReliOn N at Walmart ~$25/vial provides critical affordability.",
        usage_statistics: { popularity_rank: 14, monthly_prescriptions: 280000, user_satisfaction: 3.7 },
        fda_status: "Approved",
        rating_avg: 3.7,
        review_count: 389,
        popularity_rank: 14,
        featured: false
      },

      // ===================== ORAL MEDICATIONS - SGLT2 INHIBITORS =====================
      {
        name: "Jardiance",
        generic_name: "Empagliflozin",
        brand_names: ["Jardiance"],
        manufacturer: "Boehringer Ingelheim / Eli Lilly",
        category: "SGLT2 Inhibitor",
        subcategory: "Oral Antidiabetic",
        description: "Jardiance is an SGLT2 inhibitor that lowers blood glucose by blocking glucose reabsorption in the kidneys. FDA-approved for cardiovascular benefit in T2D and heart failure.",
        mechanism_of_action: "Inhibits sodium-glucose co-transporter 2 in the proximal renal tubules, reducing glucose reabsorption and increasing urinary glucose excretion.",
        onset_time: "1-2 hours",
        peak_time: "1.5 hours",
        duration: "24 hours",
        typical_dosing: "10-25 mg once daily in the morning. Start at 10 mg.",
        administration_route: "Oral",
        fda_approval_date: "2014-08-01",
        last_updated_date: "2023-11-20",
        avg_price: 578.88,
        medicare_price: 520.00,
        insurance_coverage_notes: "May require prior authorization. Cardiovascular indication helps coverage.",
        common_side_effects: ["UTIs", "Genital yeast infections", "Increased urination", "Thirst", "Low blood pressure"],
        serious_warnings: ["Diabetic ketoacidosis (including euglycemic DKA)", "Fournier's gangrene (rare)", "Acute kidney injury", "Lower limb amputations (class effect)"],
        contraindications: ["Severe renal impairment for glycemic control", "Dialysis", "History of serious hypersensitivity"],
        storage_requirements: "Room temperature. Protect from moisture.",
        key_features: ["Cardiovascular mortality benefit proven", "Weight loss effect", "Blood pressure reduction", "Once daily"],
        pros: ["CV protection", "Weight loss", "BP lowering", "Low hypo risk"],
        cons: ["Genital infections", "DKA risk", "Expensive", "UTI risk"],
        future_developments: "Studies ongoing in T1D, heart failure with preserved EF, and CKD.",
        clinical_notes: "First SGLT2i to show CV mortality benefit. Standard of care for T2D with CVD. Off-label use in T1D growing but risky.",
        usage_statistics: { popularity_rank: 16, monthly_prescriptions: 1200000, user_satisfaction: 4.3 },
        fda_status: "Approved",
        rating_avg: 4.3,
        review_count: 1567,
        popularity_rank: 16,
        featured: true
      },
      {
        name: "Farxiga",
        generic_name: "Dapagliflozin",
        brand_names: ["Farxiga"],
        manufacturer: "AstraZeneca",
        category: "SGLT2 Inhibitor",
        subcategory: "Oral Antidiabetic",
        description: "Farxiga is an SGLT2 inhibitor with broad indications including T2D, heart failure, and chronic kidney disease.",
        mechanism_of_action: "Inhibits SGLT2 to increase urinary glucose excretion and reduce blood glucose levels.",
        onset_time: "2 hours",
        peak_time: "2 hours",
        duration: "24 hours",
        typical_dosing: "5-10 mg once daily in the morning.",
        administration_route: "Oral",
        fda_approval_date: "2014-01-08",
        last_updated_date: "2023-10-01",
        avg_price: 556.32,
        medicare_price: 500.00,
        insurance_coverage_notes: "Covered for multiple indications. Prior auth may apply.",
        common_side_effects: ["Genital mycotic infections", "UTIs", "Back pain", "Increased urination", "Dyslipidemia"],
        serious_warnings: ["DKA risk", "Dehydration", "Acute kidney injury", "Fournier's gangrene"],
        contraindications: ["Dialysis", "Severe renal impairment for glycemic use", "Hypersensitivity"],
        storage_requirements: "Room temperature.",
        key_features: ["Broadest indication label", "CKD benefit independent of diabetes", "Heart failure benefit"],
        pros: ["Multiple benefits beyond glucose", "CKD protection", "Heart failure benefit", "Weight loss"],
        cons: ["Infection risks", "DKA in T1D", "Expensive", "Not for severe CKD glycemic control"],
        future_developments: "Additional heart failure and CKD studies ongoing.",
        clinical_notes: "First SGLT2i approved for CKD without diabetes. Versatile medication with multiple benefits.",
        usage_statistics: { popularity_rank: 18, monthly_prescriptions: 980000, user_satisfaction: 4.2 },
        fda_status: "Approved",
        rating_avg: 4.2,
        review_count: 1234,
        popularity_rank: 18,
        featured: false
      },
      {
        name: "Invokana",
        generic_name: "Canagliflozin",
        brand_names: ["Invokana"],
        manufacturer: "Janssen",
        category: "SGLT2 Inhibitor",
        subcategory: "Oral Antidiabetic",
        description: "Invokana was the first SGLT2 inhibitor approved in the US. It lowers blood glucose through increased urinary excretion.",
        mechanism_of_action: "SGLT2 inhibition leading to reduced renal glucose reabsorption.",
        onset_time: "1-2 hours",
        peak_time: "1-2 hours",
        duration: "24 hours",
        typical_dosing: "100-300 mg once daily before first meal of the day.",
        administration_route: "Oral",
        fda_approval_date: "2013-03-29",
        last_updated_date: "2023-06-01",
        avg_price: 534.24,
        medicare_price: 480.00,
        insurance_coverage_notes: "Some plans have moved to preferred alternatives. Prior auth common.",
        common_side_effects: ["Genital infections", "UTIs", "Increased urination", "Thirst", "Constipation"],
        serious_warnings: ["Increased lower limb amputation risk (specific to canagliflozin)", "DKA", "Bone fracture risk", "Acute kidney injury"],
        contraindications: ["Dialysis", "Severe renal impairment", "Hypersensitivity"],
        storage_requirements: "Room temperature.",
        key_features: ["First SGLT2i approved", "CKD benefit shown in CREDENCE trial"],
        pros: ["Proven CKD benefit", "Weight loss", "BP reduction"],
        cons: ["Amputation risk higher than others", "Bone fracture concern", "Older in class"],
        future_developments: "Facing competition from newer SGLT2is with cleaner safety profiles.",
        clinical_notes: "CREDENCE trial showed significant CKD benefit but amputation signal has reduced prescribing.",
        usage_statistics: { popularity_rank: 22, monthly_prescriptions: 340000, user_satisfaction: 3.9 },
        fda_status: "Approved",
        rating_avg: 3.9,
        review_count: 678,
        popularity_rank: 22,
        featured: false
      },

      // ===================== ORAL MEDICATIONS - BIGUANIDES =====================
      {
        name: "Metformin",
        generic_name: "Metformin Hydrochloride",
        brand_names: ["Glucophage", "Glumetza", "Fortamet", "Riomet"],
        manufacturer: "Various (Generic)",
        category: "Biguanide",
        subcategory: "Oral Antidiabetic",
        description: "Metformin is the first-line oral medication for type 2 diabetes. It reduces hepatic glucose production and improves insulin sensitivity.",
        mechanism_of_action: "Decreases hepatic gluconeogenesis, reduces intestinal glucose absorption, and improves peripheral glucose uptake and utilization by enhancing insulin sensitivity.",
        onset_time: "1-3 hours",
        peak_time: "2-4 hours (IR), 7 hours (XR)",
        duration: "12-24 hours",
        typical_dosing: "Start 500 mg twice daily with meals. Maximum 2550 mg/day (IR) or 2000 mg/day (XR).",
        administration_route: "Oral",
        fda_approval_date: "1994-12-29",
        last_updated_date: "2023-08-15",
        avg_price: 15.00,
        medicare_price: 4.00,
        insurance_coverage_notes: "Tier 1 on virtually all formularies. Extremely affordable.",
        common_side_effects: ["GI upset", "Diarrhea", "Nausea", "Metallic taste", "B12 deficiency"],
        serious_warnings: ["Lactic acidosis (rare, mainly with renal impairment)", "Hold before contrast procedures", "B12 monitoring recommended"],
        contraindications: ["eGFR < 30 mL/min", "Acute or chronic metabolic acidosis", "History of lactic acidosis"],
        storage_requirements: "Room temperature. Protect from moisture.",
        key_features: ["First-line therapy", "Weight neutral or slight loss", "Potential CV benefit", "Very affordable"],
        pros: ["Extremely inexpensive", "Weight neutral", "No hypoglycemia alone", "Decades of safety data", "Potential longevity benefits"],
        cons: ["GI side effects common", "B12 deficiency", "Must hold for contrast", "Renal dose adjustment"],
        future_developments: "Studies ongoing for longevity, cancer prevention, and other metabolic conditions.",
        clinical_notes: "Foundation of T2D treatment. Extended-release formulation reduces GI side effects significantly.",
        usage_statistics: { popularity_rank: 17, monthly_prescriptions: 8500000, user_satisfaction: 4.0 },
        fda_status: "Approved",
        rating_avg: 4.0,
        review_count: 4567,
        popularity_rank: 17,
        featured: true
      },

      // ===================== ORAL MEDICATIONS - DPP-4 INHIBITORS =====================
      {
        name: "Januvia",
        generic_name: "Sitagliptin",
        brand_names: ["Januvia"],
        manufacturer: "Merck",
        category: "DPP-4 Inhibitor",
        subcategory: "Oral Antidiabetic",
        description: "Januvia is a DPP-4 inhibitor that enhances the body's own incretin hormones to regulate blood sugar after meals.",
        mechanism_of_action: "Inhibits dipeptidyl peptidase-4, which normally degrades GLP-1 and GIP. This increases active incretin levels, stimulating insulin secretion and reducing glucagon in a glucose-dependent manner.",
        onset_time: "1-4 hours",
        peak_time: "1-4 hours",
        duration: "24 hours",
        typical_dosing: "100 mg once daily. Reduce for renal impairment.",
        administration_route: "Oral",
        fda_approval_date: "2006-10-17",
        last_updated_date: "2023-07-01",
        avg_price: 489.60,
        medicare_price: 440.00,
        insurance_coverage_notes: "Well-covered but prior auth may be needed. Generic expected soon.",
        common_side_effects: ["Upper respiratory infection", "Headache", "Nasopharyngitis", "Hypoglycemia (with SU/insulin)"],
        serious_warnings: ["Acute pancreatitis risk", "Severe joint pain reported", "Heart failure hospitalization concern (class effect, mainly saxagliptin)"],
        contraindications: ["History of serious hypersensitivity to sitagliptin", "History of pancreatitis (relative)"],
        storage_requirements: "Room temperature.",
        key_features: ["Weight neutral", "Low hypoglycemia risk", "Once daily", "Can use in renal impairment with adjustment"],
        pros: ["Weight neutral", "Well-tolerated", "Low hypo risk", "Once daily", "Good for elderly"],
        cons: ["Modest A1c reduction", "Expensive", "Pancreatitis concern", "Less potent than GLP-1s"],
        future_developments: "Patent expiration expected to bring generics and price reduction.",
        clinical_notes: "Good option for patients who cannot tolerate metformin or need weight-neutral therapy. Less potent than GLP-1 agonists.",
        usage_statistics: { popularity_rank: 21, monthly_prescriptions: 890000, user_satisfaction: 4.0 },
        fda_status: "Approved",
        rating_avg: 4.0,
        review_count: 1123,
        popularity_rank: 21,
        featured: false
      },
      {
        name: "Tradjenta",
        generic_name: "Linagliptin",
        brand_names: ["Tradjenta"],
        manufacturer: "Boehringer Ingelheim / Eli Lilly",
        category: "DPP-4 Inhibitor",
        subcategory: "Oral Antidiabetic",
        description: "Tradjenta is a DPP-4 inhibitor unique for its primarily non-renal elimination, requiring no dose adjustment for kidney disease.",
        mechanism_of_action: "Same as other DPP-4 inhibitors. Increases incretin levels to enhance glucose-dependent insulin secretion.",
        onset_time: "1-2 hours",
        peak_time: "1.5 hours",
        duration: "24 hours",
        typical_dosing: "5 mg once daily. No renal dose adjustment needed.",
        administration_route: "Oral",
        fda_approval_date: "2011-05-02",
        last_updated_date: "2023-04-15",
        avg_price: 467.04,
        medicare_price: 420.00,
        insurance_coverage_notes: "May require prior auth. Valued for CKD patients.",
        common_side_effects: ["Nasopharyngitis", "Hyperlipidemia", "Cough", "Hypoglycemia (with SU/insulin)"],
        serious_warnings: ["Acute pancreatitis", "Severe joint pain", "Bullous pemphigoid (rare)"],
        contraindications: ["Serious hypersensitivity to linagliptin"],
        storage_requirements: "Room temperature.",
        key_features: ["No renal dose adjustment ever", "Hepatic elimination", "Good for CKD patients"],
        pros: ["No renal adjustment", "Weight neutral", "Once daily", "Safe in severe CKD"],
        cons: ["Expensive", "Modest efficacy", "Pancreatitis concern"],
        future_developments: "Continued role in CKD population where GLP-1s may be limited.",
        clinical_notes: "Preferred DPP-4i for patients with kidney disease due to no dose adjustment requirement.",
        usage_statistics: { popularity_rank: 25, monthly_prescriptions: 340000, user_satisfaction: 4.0 },
        fda_status: "Approved",
        rating_avg: 4.0,
        review_count: 456,
        popularity_rank: 25,
        featured: false
      },

      // ===================== GLP-1 RECEPTOR AGONISTS =====================
      {
        name: "Ozempic",
        generic_name: "Semaglutide",
        brand_names: ["Ozempic"],
        manufacturer: "Novo Nordisk",
        category: "GLP-1 Receptor Agonist",
        subcategory: "Injectable Antidiabetic",
        description: "Ozempic is a once-weekly GLP-1 receptor agonist providing powerful glycemic control with significant weight loss and cardiovascular benefits.",
        mechanism_of_action: "Mimics GLP-1, stimulating glucose-dependent insulin secretion, suppressing glucagon, slowing gastric emptying, and reducing appetite through central nervous system effects.",
        onset_time: "1-3 days",
        peak_time: "1-3 days",
        duration: "7 days",
        typical_dosing: "Start 0.25 mg weekly for 4 weeks, increase to 0.5 mg, then 1 mg, maximum 2 mg weekly.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2017-12-05",
        last_updated_date: "2023-12-15",
        avg_price: 935.77,
        medicare_price: 850.00,
        insurance_coverage_notes: "May require prior authorization. High demand causes shortages.",
        common_side_effects: ["Nausea", "Vomiting", "Diarrhea", "Abdominal pain", "Constipation", "Decreased appetite"],
        serious_warnings: ["Thyroid C-cell tumors in rodents (boxed warning)", "Pancreatitis", "Diabetic retinopathy complications", "Acute kidney injury", "Gallbladder disease"],
        contraindications: ["Personal or family history of MTC", "MEN 2 syndrome", "Serious hypersensitivity"],
        storage_requirements: "Refrigerate before first use. Room temperature for 56 days after first use.",
        key_features: ["Once weekly", "Powerful A1c reduction (1.5-2%)", "Significant weight loss (10-15%)", "CV mortality benefit proven"],
        pros: ["Once weekly", "Major weight loss", "Strong A1c reduction", "CV protection", "Appetite suppression"],
        cons: ["GI side effects common initially", "Expensive", "Shortages", "Thyroid warning", "Muscle loss concern"],
        future_developments: "Higher doses in development. CagriSema (with cagrilintide) in trials.",
        clinical_notes: "Most prescribed GLP-1. Demand exceeds supply. Transformative for T2D with obesity. Off-label weight loss use common.",
        usage_statistics: { popularity_rank: 19, monthly_prescriptions: 2100000, user_satisfaction: 4.5 },
        fda_status: "Approved",
        rating_avg: 4.5,
        review_count: 3456,
        popularity_rank: 19,
        featured: true
      },
      {
        name: "Mounjaro",
        generic_name: "Tirzepatide",
        brand_names: ["Mounjaro"],
        manufacturer: "Eli Lilly",
        category: "Dual GIP/GLP-1 Agonist",
        subcategory: "Injectable Antidiabetic",
        description: "Mounjaro is the first dual GIP and GLP-1 receptor agonist, providing the most potent glycemic control and weight loss of any approved diabetes medication.",
        mechanism_of_action: "Activates both GIP and GLP-1 receptors, providing synergistic effects on insulin secretion, glucagon suppression, gastric emptying, and appetite regulation.",
        onset_time: "8-72 hours",
        peak_time: "8-72 hours",
        duration: "7 days",
        typical_dosing: "Start 2.5 mg weekly, increase by 2.5 mg every 4 weeks to 5 mg, 7.5 mg, 10 mg, 12.5 mg, or max 15 mg.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2022-05-13",
        last_updated_date: "2023-11-01",
        avg_price: 1023.04,
        medicare_price: 920.00,
        insurance_coverage_notes: "Prior authorization required. Coverage improving as data accumulates.",
        common_side_effects: ["Nausea", "Diarrhea", "Decreased appetite", "Vomiting", "Constipation", "Abdominal pain"],
        serious_warnings: ["Thyroid C-cell tumors (boxed warning)", "Pancreatitis", "Hypoglycemia with insulin/SU", "Acute gallbladder disease", "Acute kidney injury"],
        contraindications: ["Personal or family history of MTC", "MEN 2 syndrome", "Serious hypersensitivity"],
        storage_requirements: "Refrigerate. Can be at room temperature for 21 days.",
        key_features: ["First-in-class dual agonist", "Most powerful A1c reduction (up to 2.4%)", "Most weight loss (up to 22%)", "Once weekly"],
        pros: ["Most effective for A1c and weight", "Once weekly", "Novel mechanism", "Potential CV benefits"],
        cons: ["Most expensive", "GI side effects", "Newer with less long-term data", "Shortages", "Muscle loss concern"],
        future_developments: "CV outcome trial SURPASS-CVOT ongoing. Zepbound approved for obesity. Oral formulation in development.",
        clinical_notes: "Most potent diabetes medication available. Game-changer for T2D with obesity. SURMOUNT trials showed 22% weight loss.",
        usage_statistics: { popularity_rank: 20, monthly_prescriptions: 890000, user_satisfaction: 4.7 },
        fda_status: "Approved",
        rating_avg: 4.7,
        review_count: 1234,
        popularity_rank: 20,
        featured: true
      },
      {
        name: "Trulicity",
        generic_name: "Dulaglutide",
        brand_names: ["Trulicity"],
        manufacturer: "Eli Lilly",
        category: "GLP-1 Receptor Agonist",
        subcategory: "Injectable Antidiabetic",
        description: "Trulicity is a once-weekly GLP-1 receptor agonist with proven cardiovascular benefits and user-friendly delivery device.",
        mechanism_of_action: "GLP-1 receptor activation enhancing glucose-dependent insulin secretion and suppressing glucagon.",
        onset_time: "24-72 hours",
        peak_time: "24-72 hours",
        duration: "7 days",
        typical_dosing: "Start 0.75 mg weekly, may increase to 1.5 mg, 3 mg, or max 4.5 mg weekly.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2014-09-18",
        last_updated_date: "2023-08-01",
        avg_price: 886.56,
        medicare_price: 800.00,
        insurance_coverage_notes: "Well-covered. Often preferred tier over newer options.",
        common_side_effects: ["Nausea", "Diarrhea", "Vomiting", "Abdominal pain", "Decreased appetite"],
        serious_warnings: ["Thyroid C-cell tumors (boxed warning)", "Pancreatitis", "Hypoglycemia", "Acute kidney injury"],
        contraindications: ["Personal or family history of MTC", "MEN 2", "Hypersensitivity"],
        storage_requirements: "Refrigerate. Room temperature up to 14 days.",
        key_features: ["Hidden needle device", "CV benefit proven in REWIND", "No injection training needed"],
        pros: ["Easy-to-use device", "Hidden needle", "CV protection", "Once weekly", "Strong data"],
        cons: ["Less weight loss than semaglutide", "GI side effects", "Expensive"],
        future_developments: "Continued positioning as entry-level GLP-1 with strong CV data.",
        clinical_notes: "Excellent option for injection-naive patients. REWIND showed 12% CV risk reduction.",
        usage_statistics: { popularity_rank: 23, monthly_prescriptions: 780000, user_satisfaction: 4.3 },
        fda_status: "Approved",
        rating_avg: 4.3,
        review_count: 1567,
        popularity_rank: 23,
        featured: false
      },
      {
        name: "Victoza",
        generic_name: "Liraglutide",
        brand_names: ["Victoza"],
        manufacturer: "Novo Nordisk",
        category: "GLP-1 Receptor Agonist",
        subcategory: "Injectable Antidiabetic",
        description: "Victoza is a daily GLP-1 receptor agonist with established cardiovascular benefits and extensive safety data.",
        mechanism_of_action: "GLP-1 analog with 97% homology to native GLP-1, providing sustained receptor activation.",
        onset_time: "8-12 hours",
        peak_time: "8-12 hours",
        duration: "24 hours",
        typical_dosing: "Start 0.6 mg daily for 1 week, increase to 1.2 mg, max 1.8 mg daily.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2010-01-25",
        last_updated_date: "2023-03-15",
        avg_price: 943.20,
        medicare_price: 850.00,
        insurance_coverage_notes: "Covered but often requires step through weekly options first.",
        common_side_effects: ["Nausea", "Diarrhea", "Headache", "Vomiting", "Decreased appetite"],
        serious_warnings: ["Thyroid C-cell tumors (boxed warning)", "Pancreatitis", "Hypoglycemia", "Renal impairment"],
        contraindications: ["Personal or family history of MTC", "MEN 2", "Hypersensitivity"],
        storage_requirements: "Refrigerate before first use. Room temperature 30 days after.",
        key_features: ["LEADER trial showed CV mortality benefit", "Extensive real-world data", "Daily dosing provides flexibility"],
        pros: ["Proven CV mortality benefit", "Long safety record", "Flexible daily dosing"],
        cons: ["Daily injection", "Less weight loss than semaglutide", "Being replaced by weekly options"],
        future_developments: "Largely superseded by Ozempic in new starts but remains important option.",
        clinical_notes: "First GLP-1 with CV mortality benefit (LEADER). Still valuable for patients preferring daily dosing.",
        usage_statistics: { popularity_rank: 26, monthly_prescriptions: 320000, user_satisfaction: 4.1 },
        fda_status: "Approved",
        rating_avg: 4.1,
        review_count: 987,
        popularity_rank: 26,
        featured: false
      },
      {
        name: "Rybelsus",
        generic_name: "Oral Semaglutide",
        brand_names: ["Rybelsus"],
        manufacturer: "Novo Nordisk",
        category: "GLP-1 Receptor Agonist",
        subcategory: "Oral Antidiabetic",
        description: "Rybelsus is the first and only oral GLP-1 receptor agonist, providing an alternative to injections with the same semaglutide molecule as Ozempic.",
        mechanism_of_action: "Same as injectable semaglutide but formulated with SNAC absorption enhancer for oral delivery.",
        onset_time: "Variable",
        peak_time: "1 hour",
        duration: "24 hours",
        typical_dosing: "Start 3 mg daily for 30 days, increase to 7 mg, then 14 mg if needed. Must be taken fasting with ≤4 oz water.",
        administration_route: "Oral",
        fda_approval_date: "2019-09-20",
        last_updated_date: "2023-09-01",
        avg_price: 935.77,
        medicare_price: 850.00,
        insurance_coverage_notes: "Prior authorization common. May require step through other orals first.",
        common_side_effects: ["Nausea", "Abdominal pain", "Diarrhea", "Decreased appetite", "Vomiting", "Constipation"],
        serious_warnings: ["Thyroid C-cell tumors (boxed warning)", "Pancreatitis", "Strict dosing requirements", "Diabetic retinopathy"],
        contraindications: ["Personal or family history of MTC", "MEN 2", "Hypersensitivity"],
        storage_requirements: "Room temperature. Keep in original packaging until use.",
        key_features: ["First oral GLP-1", "No injections", "Same molecule as Ozempic", "Convenient for injection-averse patients"],
        pros: ["No injection required", "GLP-1 efficacy", "Semaglutide benefits orally"],
        cons: ["Strict taking requirements (fasting, water only, wait 30 min)", "Less weight loss than injection", "Absorption variable", "Expensive"],
        future_developments: "Higher oral doses in development for obesity indication.",
        clinical_notes: "Great option for needle-phobic patients. Strict administration rules critical for efficacy. Less potent than injectable semaglutide at current doses.",
        usage_statistics: { popularity_rank: 24, monthly_prescriptions: 450000, user_satisfaction: 4.0 },
        fda_status: "Approved",
        rating_avg: 4.0,
        review_count: 678,
        popularity_rank: 24,
        featured: false
      },

      // ===================== SULFONYLUREAS =====================
      {
        name: "Glipizide",
        generic_name: "Glipizide",
        brand_names: ["Glucotrol", "Glucotrol XL"],
        manufacturer: "Various (Generic)",
        category: "Sulfonylurea",
        subcategory: "Oral Antidiabetic",
        description: "Glipizide is a sulfonylurea that stimulates insulin release from the pancreas, used for type 2 diabetes.",
        mechanism_of_action: "Binds to sulfonylurea receptor on beta cells, closing ATP-sensitive potassium channels and triggering insulin release.",
        onset_time: "1-3 hours",
        peak_time: "1-3 hours (IR), 6-12 hours (XL)",
        duration: "12-24 hours",
        typical_dosing: "Start 5 mg before breakfast. Maximum 40 mg/day divided doses (IR) or 20 mg/day (XL).",
        administration_route: "Oral",
        fda_approval_date: "1984-05-25",
        last_updated_date: "2022-01-15",
        avg_price: 12.00,
        medicare_price: 4.00,
        insurance_coverage_notes: "Tier 1 generic. Extremely affordable.",
        common_side_effects: ["Hypoglycemia", "Weight gain", "Dizziness", "Headache", "GI upset"],
        serious_warnings: ["Hypoglycemia (can be severe and prolonged)", "Cardiovascular concerns (UGDP historical)", "Avoid in severe hepatic/renal impairment"],
        contraindications: ["Type 1 diabetes", "Diabetic ketoacidosis", "Sulfonamide allergy (relative)"],
        storage_requirements: "Room temperature.",
        key_features: ["Very affordable", "Potent A1c reduction", "Shorter duration than glyburide"],
        pros: ["Very inexpensive", "Effective A1c lowering", "Established track record"],
        cons: ["Hypoglycemia risk", "Weight gain", "Beta cell burnout concern", "No CV benefit"],
        future_developments: "Usage declining in favor of newer agents but remains cost-effective option.",
        clinical_notes: "Preferred sulfonylurea due to shorter duration reducing prolonged hypoglycemia risk. Use with caution in elderly.",
        usage_statistics: { popularity_rank: 27, monthly_prescriptions: 2800000, user_satisfaction: 3.7 },
        fda_status: "Approved",
        rating_avg: 3.7,
        review_count: 890,
        popularity_rank: 27,
        featured: false
      },
      {
        name: "Glimepiride",
        generic_name: "Glimepiride",
        brand_names: ["Amaryl"],
        manufacturer: "Various (Generic)",
        category: "Sulfonylurea",
        subcategory: "Oral Antidiabetic",
        description: "Glimepiride is a long-acting sulfonylurea for type 2 diabetes, offering once-daily dosing.",
        mechanism_of_action: "Sulfonylurea receptor binding causing insulin release. Also may have extrapancreatic effects on insulin sensitivity.",
        onset_time: "2-3 hours",
        peak_time: "2-3 hours",
        duration: "24 hours",
        typical_dosing: "Start 1-2 mg once daily with first main meal. Maximum 8 mg/day.",
        administration_route: "Oral",
        fda_approval_date: "1995-11-07",
        last_updated_date: "2022-03-01",
        avg_price: 18.00,
        medicare_price: 4.00,
        insurance_coverage_notes: "Tier 1 generic. Inexpensive.",
        common_side_effects: ["Hypoglycemia", "Weight gain", "Dizziness", "Weakness", "GI upset"],
        serious_warnings: ["Hypoglycemia (may be prolonged)", "Increased cardiovascular risk in some studies", "Cross-sensitivity with sulfonamides"],
        contraindications: ["Type 1 diabetes", "DKA", "Sulfonamide allergy"],
        storage_requirements: "Room temperature.",
        key_features: ["Once daily dosing", "Potent effect", "May have some extrapancreatic benefits"],
        pros: ["Once daily", "Inexpensive", "Effective"],
        cons: ["Prolonged hypoglycemia risk", "Weight gain", "CV concerns"],
        future_developments: "Decreasing use as GLP-1s and SGLT2is become more accessible.",
        clinical_notes: "Once-daily sulfonylurea option. Longer duration than glipizide means more hypoglycemia risk.",
        usage_statistics: { popularity_rank: 28, monthly_prescriptions: 1900000, user_satisfaction: 3.6 },
        fda_status: "Approved",
        rating_avg: 3.6,
        review_count: 567,
        popularity_rank: 28,
        featured: false
      },

      // ===================== AMYLIN ANALOG =====================
      {
        name: "Symlin",
        generic_name: "Pramlintide",
        brand_names: ["Symlin", "SymlinPen"],
        manufacturer: "AstraZeneca",
        category: "Amylin Analog",
        subcategory: "Injectable Antidiabetic",
        description: "Symlin is a synthetic amylin analog used alongside insulin to improve postprandial glucose control and reduce insulin requirements.",
        mechanism_of_action: "Mimics amylin, a hormone co-secreted with insulin. Slows gastric emptying, reduces postprandial glucagon, and promotes satiety.",
        onset_time: "15-20 minutes",
        peak_time: "20-45 minutes",
        duration: "3 hours",
        typical_dosing: "T1D: Start 15 mcg before meals, increase by 15 mcg to max 60 mcg. T2D: Start 60 mcg, increase to 120 mcg.",
        administration_route: "Subcutaneous injection",
        fda_approval_date: "2005-03-16",
        last_updated_date: "2022-09-01",
        avg_price: 1245.12,
        medicare_price: 1100.00,
        insurance_coverage_notes: "Poor coverage. Often tier 4 or not covered. Prior auth required.",
        common_side_effects: ["Nausea", "Vomiting", "Anorexia", "Headache", "Injection site reactions"],
        serious_warnings: ["Severe hypoglycemia (requires 50% insulin reduction at start)", "Do not mix with insulin", "Nausea usually transient"],
        contraindications: ["Hypoglycemia unawareness", "Gastroparesis", "Poor compliance potential", "HbA1c > 9%"],
        storage_requirements: "Refrigerate. Room temperature up to 30 days.",
        key_features: ["Only FDA-approved for T1D beyond insulin", "Reduces post-meal spikes", "May aid weight management"],
        pros: ["Reduces postprandial spikes", "Weight loss", "Reduces insulin needs", "Only non-insulin for T1D"],
        cons: ["Additional injection", "Severe hypo risk", "Very expensive", "Poor insurance coverage", "Nausea"],
        future_developments: "Amylin research ongoing in combination with other hormones for T1D.",
        clinical_notes: "Underutilized in T1D due to complexity. Requires motivated patients willing to manage hypo risk. Helpful for stubborn post-meal spikes.",
        usage_statistics: { popularity_rank: 35, monthly_prescriptions: 15000, user_satisfaction: 3.8 },
        fda_status: "Approved",
        rating_avg: 3.8,
        review_count: 123,
        popularity_rank: 35,
        featured: false
      }
    ];

    // Add external reviews for popular medications
    const externalReviews = [
      // Novolog reviews
      {
        medication_name: "Novolog",
        source: "reddit",
        subreddit: "r/diabetes_t1",
        author_anonymous: "T1D_warrior",
        title: "Novolog has been my go-to for 10 years",
        content: "Switched to Novolog from Humalog about 10 years ago and never looked back. The onset is slightly faster for me, which helps with those post-meal spikes. Works great in my Tandem pump too. The FlexTouch pens are super easy to use when I need to MDI.",
        sentiment: "positive",
        helpful_count: 45
      },
      {
        medication_name: "Novolog",
        source: "reddit",
        subreddit: "r/diabetes",
        author_anonymous: "pumper_life",
        title: "Pump compatibility is excellent",
        content: "Been using Novolog in my OmniPod for 3 years. Very reliable, rarely any occlusion issues. The cartridges work well and I've had consistent absorption. Only downside is the cost without insurance is brutal.",
        sentiment: "positive",
        helpful_count: 32
      },
      // Ozempic reviews
      {
        medication_name: "Ozempic",
        source: "reddit",
        subreddit: "r/diabetes_t2",
        author_anonymous: "ozempic_changed_my_life",
        title: "Lost 40 lbs and A1c dropped from 8.5 to 5.9",
        content: "Started Ozempic 8 months ago. The nausea was rough for the first month but it got better. I've lost 40 pounds without really trying - my appetite is just so much less. A1c went from 8.5 to 5.9! The weekly injection is so easy. Best decision my endo ever made.",
        sentiment: "positive",
        helpful_count: 234
      },
      {
        medication_name: "Ozempic",
        source: "reddit",
        subreddit: "r/Ozempic",
        author_anonymous: "side_effect_struggle",
        title: "GI side effects are real but manageable",
        content: "Month 2 on Ozempic. The 'Ozempic burps' are real and kind of sulfury. Constipation has been my biggest issue - take fiber and magnesium people! But my blood sugars are amazing and I've already lost 15 lbs so I'm pushing through.",
        sentiment: "neutral",
        helpful_count: 156
      },
      // Mounjaro reviews
      {
        medication_name: "Mounjaro",
        source: "reddit",
        subreddit: "r/Mounjaro",
        author_anonymous: "tirzepatide_fan",
        title: "From A1c 9.2 to 5.4 in 6 months - unbelievable",
        content: "I've tried everything - metformin, Trulicity, Jardiance. Nothing worked like Mounjaro. My A1c was 9.2 when I started. Six months later: 5.4. I've lost 55 pounds. The nausea was bad weeks 1-3 of each dose increase but totally worth it. This drug is a miracle.",
        sentiment: "positive",
        helpful_count: 312
      },
      {
        medication_name: "Mounjaro",
        source: "reddit",
        subreddit: "r/diabetes_t2",
        author_anonymous: "mounjaro_skeptic_converted",
        title: "Was skeptical but results speak for themselves",
        content: "Doctor pushed hard for Mounjaro and I was skeptical of the hype. Started at 2.5mg 4 months ago, now on 10mg. Down 35 lbs, A1c from 7.8 to 5.7, off my glipizide completely. The food noise is just... gone. Only wish insurance covered it better.",
        sentiment: "positive",
        helpful_count: 198
      },
      // Lantus reviews
      {
        medication_name: "Lantus",
        source: "reddit",
        subreddit: "r/diabetes_t1",
        author_anonymous: "basal_queen",
        title: "Lantus vs Tresiba - my comparison",
        content: "Used Lantus for 15 years before trying Tresiba. Lantus works well but I did split my dose because I'd always go low around hour 18-20. Switching to Tresiba eliminated that. But Lantus is much cheaper with my insurance so it's a trade-off. Both are solid.",
        sentiment: "neutral",
        helpful_count: 89
      },
      {
        medication_name: "Lantus",
        source: "reddit",
        subreddit: "r/diabetes",
        author_anonymous: "long_timer",
        title: "20 years on Lantus - still works",
        content: "Been on Lantus since it came out. Never had any issues. Take it at bedtime, wake up with decent numbers. Sure, newer insulins might be better but if it ain't broke... The SoloStar pens are reliable. Stings a bit but not a big deal.",
        sentiment: "positive",
        helpful_count: 67
      },
      // Fiasp reviews
      {
        medication_name: "Fiasp",
        source: "reddit",
        subreddit: "r/diabetes_t1",
        author_anonymous: "fiasp_convert",
        title: "Fiasp dramatically improved my post-meal spikes",
        content: "Switched from Novolog to Fiasp 6 months ago. The difference in post-meal spikes is incredible. I used to spike to 200+ after pizza. Now I rarely go above 160. The faster onset means I can dose when I sit down to eat instead of 15 min before. Game changer.",
        sentiment: "positive",
        helpful_count: 145
      },
      // Tresiba reviews  
      {
        medication_name: "Tresiba",
        source: "reddit",
        subreddit: "r/diabetes_t1",
        author_anonymous: "tresiba_believer",
        title: "Finally stable overnight sugars with Tresiba",
        content: "After years of overnight lows and dawn phenomenon on Lantus, switched to Tresiba. The difference is night and day (literally). My overnight BGs are flat. The 42+ hour duration means if I'm a few hours late on my dose, it doesn't matter. Worth every penny.",
        sentiment: "positive",
        helpful_count: 178
      },
      // Metformin reviews
      {
        medication_name: "Metformin",
        source: "reddit",
        subreddit: "r/diabetes_t2",
        author_anonymous: "metformin_stomach",
        title: "GI side effects rough but XR version helped",
        content: "Started on regular metformin 500mg twice a day. The bathroom issues were real - couldn't be far from a toilet for 2 months. Switched to metformin XR and it's so much better. Barely any GI issues now. A1c dropped from 7.2 to 6.4 after 6 months. Cheap and effective.",
        sentiment: "neutral",
        helpful_count: 123
      },
      // Jardiance reviews
      {
        medication_name: "Jardiance",
        source: "reddit",
        subreddit: "r/diabetes_t2",
        author_anonymous: "jardiance_heart_helper",
        title: "Cardiologist recommended it and I'm glad",
        content: "My cardiologist added Jardiance after my heart attack. Not only has my A1c improved (7.1 to 6.3) but I've lost 12 lbs and my blood pressure is better. Had one yeast infection early on but it went away. The heart protection is the main reason I take it. Also makes me pee a lot!",
        sentiment: "positive",
        helpful_count: 87
      }
    ];

    // Clear existing data
    console.log('Clearing existing medication data...');
    await supabase.from('external_medication_reviews').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('medication_reviews').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('medications').delete().neq('id', '00000000-0000-0000-0000-000000000000');

    // Insert medications
    console.log('Inserting medications...');
    const { data: insertedMeds, error: medError } = await supabase
      .from('medications')
      .insert(medications)
      .select();

    if (medError) {
      console.error('Error inserting medications:', medError);
      throw medError;
    }

    console.log(`Successfully inserted ${insertedMeds?.length || 0} medications`);

    // Create medication name to ID mapping
    const medMap = new Map();
    insertedMeds?.forEach(med => {
      medMap.set(med.name, med.id);
    });

    // Insert external reviews with medication IDs
    const reviewsWithIds = externalReviews
      .filter(review => medMap.has(review.medication_name))
      .map(review => ({
        medication_id: medMap.get(review.medication_name),
        source: review.source,
        subreddit: review.subreddit,
        author_anonymous: review.author_anonymous,
        title: review.title,
        content: review.content,
        sentiment: review.sentiment,
        helpful_count: review.helpful_count,
        published_at: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString()
      }));

    console.log('Inserting external reviews...');
    const { data: insertedReviews, error: reviewError } = await supabase
      .from('external_medication_reviews')
      .insert(reviewsWithIds)
      .select();

    if (reviewError) {
      console.error('Error inserting external reviews:', reviewError);
    } else {
      console.log(`Successfully inserted ${insertedReviews?.length || 0} external reviews`);
    }

    // Get category counts
    const categoryCounts: Record<string, number> = {};
    medications.forEach(med => {
      categoryCounts[med.category] = (categoryCounts[med.category] || 0) + 1;
    });

    return new Response(
      JSON.stringify({
        success: true,
        medications_created: insertedMeds?.length || 0,
        external_reviews_created: insertedReviews?.length || 0,
        categories: categoryCounts,
        featured_count: medications.filter(m => m.featured).length
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error: unknown) {
    console.error('Error in seed-medications:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
