import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Clear existing posts first
    await supabase.from("adult_content_posts").delete().neq("id", "00000000-0000-0000-0000-000000000000");

    const posts = [
      // ===== INTIMACY & SEX (20 posts) =====
      {
        title: "Sex with Type 1 Diabetes: The Challenges and the Solutions",
        content: "Been T1D for 12 years. Here's what I've learned about managing intimacy: 1) Always check BG before. Below 100? Have a snack. 2) CGM on your arm is way better than stomach for intimate situations. 3) Disconnect your pump if tubing gets in the way — 30-60 min without basal is usually fine. 4) Keep glucose tabs on the nightstand, not buried in a drawer. 5) Communication with your partner is everything. Most people are way more understanding than you'd expect.",
        category: "intimacy",
        source_url: "https://www.reddit.com/r/Type1Diabetes/comments/1cd7rb7/sex_with_type_1_diabetes_the_challenges_and_the/",
        source_platform: "Reddit",
        author_username: "t1d_reallife",
        comments_count: 47,
        upvotes: 312,
        tips: ["Check BG before — aim for 120-180 range", "Keep glucose tabs on nightstand", "CGM placement on arm avoids contact issues", "Disconnect pump for 30-60 min if needed"],
        warnings: ["Don't ignore a CGM low alarm during intimacy", "Reconnect pump within 1 hour"],
        topic_tags: ["cgm_during_sex", "pump_management", "blood_sugar_management"],
        sentiment: "positive",
        confidence_score: 0.92,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "NSFW: Diabetes and sex — the real talk nobody gives you",
        content: "Diagnosed at 8, now 27. Nobody told me diabetes would affect my sex life. Lows during sex are real and terrifying. I've had to stop mid-act because my Dexcom started screaming. My partner now knows what the alarms mean and keeps juice boxes nearby. It took a while to not feel embarrassed but honestly, being open about it made our relationship stronger. The biggest myth is that diabetes makes you 'broken' — it doesn't. It just means you need a game plan.",
        category: "intimacy",
        source_url: "https://www.reddit.com/r/diabetes_t1/comments/8mxuyo/nsfw_diabetes_and_sex/",
        source_platform: "Reddit",
        author_username: "dx_age8_warrior",
        comments_count: 89,
        upvotes: 456,
        tips: ["Educate your partner on alarms and what they mean", "Keep fast-acting sugar within arm's reach", "Don't feel ashamed — it's a medical condition, not a flaw"],
        warnings: ["Never silence a low alarm — always treat first", "Adrenaline can mask low symptoms during intimacy"],
        topic_tags: ["lows_during_sex", "partner_education", "emotional_health"],
        sentiment: "positive",
        confidence_score: 0.88,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Casual sex with diabetes — how do you handle disclosure?",
        content: "I'm 24F and recently single. The hookup scene is intimidating enough without having to explain why I have a robot attached to my body. I usually wait until things are getting physical to mention it casually — 'oh that's my insulin pump, don't worry about it.' Most guys don't care at all. One guy thought my Dexcom was a nicotine patch lol. The bigger challenge is managing the blood sugar roller coaster from nerves + activity. I always run a temp basal of -30% before a date.",
        category: "intimacy",
        source_url: "https://www.reddit.com/r/diabetes/comments/1hr09cs/casual_sex_with_diabetes/",
        source_platform: "Reddit",
        author_username: "single_and_diabetic",
        comments_count: 63,
        upvotes: 289,
        tips: ["Casual mention works better than a formal disclosure", "Run temp basal reduction before physically active dates", "Most people genuinely don't care about devices"],
        warnings: ["Don't skip insulin management to hide your condition", "Be mindful of highs from stress/nerves too"],
        topic_tags: ["disclosure_to_partners", "dating_with_t1d", "pump_visibility"],
        sentiment: "positive",
        confidence_score: 0.85,
        post_type: "post",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Sex as a Type 1 — what I wish someone told me",
        content: "30M, diagnosed at 14. Things nobody warns you about: 1) Exercise-induced lows apply to sex too. Your BG can crash 30-60 min AFTER. 2) ED can happen to young T1Ds — high A1C over years damages blood vessels. Get checked, don't be embarrassed. 3) If you use a pump with tubing, figure out clip-on vs disconnect beforehand. Nothing kills the mood like getting tangled. 4) Hormones affect insulin sensitivity differently in men and women — your partner might need to understand this too if they're also T1D.",
        category: "intimacy",
        source_url: "https://www.reddit.com/r/diabetes_t1/comments/1kr6bma/sex_as_a_type_1/",
        source_platform: "Reddit",
        author_username: "t1d_since_teen",
        comments_count: 34,
        upvotes: 198,
        tips: ["Monitor BG for 1-2 hours after — delayed lows are common", "Talk to your endo about ED openly, treatments exist", "Practice pump management before the moment"],
        warnings: ["Chronic high blood sugar increases ED risk significantly", "Post-activity lows can be severe — always have glucose nearby"],
        topic_tags: ["erectile_dysfunction", "delayed_lows", "pump_management"],
        sentiment: "neutral",
        confidence_score: 0.9,
        post_type: "post",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Sex life with T1D — sharing my experiences after 15 years",
        content: "Been T1D since I was 11, now 26. My sex life is honestly fine, but it took years to figure out. Key learnings: Libre sensor on upper arm is the best spot — doesn't get in the way at all. I tried stomach and it got ripped off once (ouch and expensive). For women: your cycle WILL affect your blood sugars and therefore your intimate experiences. Week before period, I need 20% more insulin. During, I crash easily. Track the patterns. For everyone: post-sex lows are real. I always eat 15-20g carbs after.",
        category: "intimacy",
        source_url: "https://www.reddit.com/r/diabetes_t1/comments/9k9a4r/sex_life_with_t1d/",
        source_platform: "Reddit",
        author_username: "libre_life_26",
        comments_count: 52,
        upvotes: 267,
        tips: ["Upper arm sensor placement prevents ripping during intimacy", "Track menstrual cycle effects on insulin needs", "Eat 15-20g carbs after to prevent delayed lows"],
        warnings: ["Sensor on stomach/torso risks getting pulled off", "Menstrual cycle can cause unpredictable swings"],
        topic_tags: ["cgm_placement", "hormonal_effects", "menstrual_cycle"],
        sentiment: "positive",
        confidence_score: 0.87,
        post_type: "post",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "NSFW: Sex with T1D — the stuff your endo won't discuss",
        content: "Let's be real: endos don't talk about this stuff. Here's the community wisdom from 200+ replies in our thread: Vaginal dryness can be a diabetes complication (high BG damages nerves). Lube is your friend, no shame. For men, maintaining good A1C is the #1 thing you can do for sexual health. Nerve damage from years of highs affects sensation and function. Both genders: staying in range (70-180) during intimate moments makes everything better. The physical performance difference between a 6.5 A1C and 9.0 A1C is noticeable.",
        category: "intimacy",
        source_url: "https://www.reddit.com/r/diabetes_t1/comments/u9tl2y/nsfw_sex_with_t1d/",
        source_platform: "Reddit",
        author_username: "community_wisdom",
        comments_count: 213,
        upvotes: 534,
        tips: ["Good A1C directly improves sexual health for all genders", "Use lubricant — dryness is a common diabetes complication", "Aim for 70-180 BG range during intimacy for best experience"],
        warnings: ["Chronic hyperglycemia causes nerve damage affecting sexual function", "Don't ignore persistent issues — talk to your doctor"],
        topic_tags: ["erectile_dysfunction", "vaginal_dryness", "nerve_damage", "a1c_impact"],
        sentiment: "neutral",
        confidence_score: 0.93,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Body image and intimacy: Living with visible devices",
        content: "I wear an Omnipod and a Dexcom. That's two visible devices on my body at all times. When I first started dating after diagnosis, I was terrified of being intimate. I thought people would find the devices gross or weird. Reality check: in 4 years of dating, not a single person has been bothered. Some are curious, some think it's cool tech. One partner called my Dexcom my 'cyborg upgrade.' The hardest part was my own insecurity, not other people's reactions. If someone can't handle a medical device, they're not worth your time.",
        category: "intimacy",
        author_username: "cyborg_and_proud",
        comments_count: 78,
        upvotes: 421,
        tips: ["Most partners are curious, not repulsed by devices", "Work on your own body acceptance first", "Humor helps — own your 'cyborg' status"],
        warnings: ["Don't avoid dating due to device anxiety — most fears are unfounded"],
        topic_tags: ["body_image", "device_visibility", "dating_with_t1d", "mental_health"],
        sentiment: "positive",
        confidence_score: 0.85,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Tandem t:slim during sex — practical tips from a couple",
        content: "My wife and I are both T1D (yes, we met at a diabetes camp). Between us we have 2 pumps and 2 CGMs. Here's our system: We both disconnect pumps and put them on the nightstand. Set phone timers for 45 min as a reminder to reconnect. We keep a shared glucose stash in the bedroom — tabs, juice, and candy. We've learned each other's low symptoms. She gets pale, I get sweaty. After 8 years together, it's second nature. The key is making diabetes management a team sport, not a solo burden.",
        category: "intimacy",
        author_username: "t1d_power_couple",
        comments_count: 41,
        upvotes: 356,
        tips: ["Set a timer to reconnect pump after disconnecting", "Keep glucose supplies in every room, especially the bedroom", "Learn your partner's low symptoms"],
        warnings: ["Don't forget to reconnect — DKA risk increases after extended disconnection"],
        topic_tags: ["pump_management", "couples_with_t1d", "blood_sugar_management"],
        sentiment: "positive",
        confidence_score: 0.91,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Erectile dysfunction at 28 — T1D's dirty secret",
        content: "I know this is hard to talk about, but I need to. I'm 28, diagnosed at 10. My A1C was above 9 for most of my teens and early 20s. I started experiencing ED at 25. My endo confirmed it's diabetes-related nerve and vascular damage. I'm now on medication and it helps, but I wish someone had told me earlier that control MATTERS for this. I've gotten my A1C down to 6.8 with a closed-loop system and the improvement has been significant. To young T1Ds: take your control seriously. Future you will thank you.",
        category: "intimacy",
        author_username: "honest_about_ed",
        comments_count: 95,
        upvotes: 478,
        tips: ["Good glycemic control in youth prevents ED later", "Closed-loop systems can dramatically improve A1C", "Medication for ED is available and effective — talk to your doctor"],
        warnings: ["Years of A1C above 8 significantly increases ED risk", "ED can appear as early as mid-20s with poor control"],
        topic_tags: ["erectile_dysfunction", "a1c_impact", "nerve_damage", "young_adults"],
        sentiment: "neutral",
        confidence_score: 0.94,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "How hormonal birth control affects my T1D management",
        content: "For anyone with ovaries and T1D — hormonal birth control can seriously change your insulin needs. When I went on the pill, my basal rates needed to increase by about 15%. When I switched to an IUD, things stabilized. During my cycle, I still see swings but they're more predictable now. My endo and I worked together to create different basal profiles for different phases of my cycle. It took about 3 months of tracking to nail down the patterns. Game changer for both BG management and intimate life.",
        category: "intimacy",
        author_username: "hormones_and_insulin",
        comments_count: 56,
        upvotes: 234,
        tips: ["Track cycle + BG together for 3+ months to find patterns", "Work with your endo to create cycle-phase basal profiles", "IUDs may provide more stable insulin needs than oral contraceptives"],
        warnings: ["Switching birth control methods requires insulin adjustment period", "Don't change birth control and insulin settings simultaneously"],
        topic_tags: ["hormonal_effects", "menstrual_cycle", "birth_control", "basal_profiles"],
        sentiment: "positive",
        confidence_score: 0.86,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Pregnancy planning with T1D: What we learned",
        content: "My wife is T1D and we just had our first baby. The pregnancy planning process was intense but worth every bit of preparation. Key things: Get A1C below 6.5 BEFORE conceiving. Her endo wanted 3 months of tight control pre-conception. Insulin needs change dramatically each trimester — first trimester she was going low constantly, third trimester she was using 3x her normal dose. The closed-loop system was a lifesaver but needed constant adjustment. Intimacy during pregnancy with T1D is its own adventure — but totally manageable with planning.",
        category: "intimacy",
        author_username: "t1d_dad_2024",
        comments_count: 72,
        upvotes: 389,
        tips: ["Pre-conception A1C goal: below 6.5 for at least 3 months", "Expect insulin needs to triple by third trimester", "Closed-loop systems help but need frequent adjustment during pregnancy"],
        warnings: ["Unplanned pregnancy with high A1C carries serious risks", "First trimester hypos can be severe — have glucose everywhere"],
        topic_tags: ["pregnancy", "family_planning", "hormonal_effects", "insulin_adjustment"],
        sentiment: "positive",
        confidence_score: 0.91,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Telling a new partner about T1D: Scripts that actually work",
        content: "After dating for years with T1D, I've found what works for disclosure. Casual approach: 'Just so you know, I'm Type 1 diabetic — that thing on my arm is basically a tiny robot that monitors my blood sugar. Pretty cool actually.' If it comes up during a meal: 'I need to take insulin for this — I have Type 1 diabetes. It's just part of my routine, like wearing glasses.' For the bedroom: 'I have some medical devices I wear — they keep me alive and healthy. They might beep sometimes, and that's normal.' The key is confidence and matter-of-fact delivery. Treating it as no big deal makes others treat it as no big deal.",
        category: "intimacy",
        author_username: "dating_scripts",
        comments_count: 88,
        upvotes: 567,
        tips: ["Confidence in delivery matters more than timing", "Compare devices to familiar tech — 'like a smartwatch for my blood sugar'", "Matter-of-fact tone prevents awkwardness"],
        warnings: ["Don't hide your condition — safety first"],
        topic_tags: ["disclosure_to_partners", "dating_with_t1d", "communication"],
        sentiment: "positive",
        confidence_score: 0.89,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Freestyle Libre sensor getting ripped off during intimacy — solutions",
        content: "I've lost 3 Libre sensors in the past year during intimate moments. At $75 each without insurance, this is not just annoying, it's expensive. What finally worked: 1) SkinTac adhesive underneath — game changer for staying power. 2) Switched from stomach to back of upper arm. 3) Overtape (the clear patches) as extra security. 4) Tegaderm patches from Amazon work just as well as brand-name overtapes for 1/4 the price. Haven't lost a sensor in 6 months now. Some people also use athletic tape for extra security during active situations.",
        category: "intimacy",
        author_username: "sensor_saver",
        comments_count: 45,
        upvotes: 234,
        tips: ["SkinTac adhesive dramatically improves sensor adhesion", "Back of upper arm is the safest placement for intimacy", "Tegaderm patches from Amazon are a cheap overtape alternative"],
        warnings: ["Never reuse a sensor that's been ripped off — contamination risk", "Report sensor losses to manufacturer — they often replace them"],
        topic_tags: ["cgm_placement", "cgm_during_sex", "sensor_adhesion", "cost_management"],
        sentiment: "positive",
        confidence_score: 0.88,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Adrenaline from intimacy masks low blood sugar symptoms",
        content: "PSA for everyone: adrenaline and endorphins released during sex can completely mask your usual low symptoms. I normally feel shaky at 65, but during intimacy I dropped to 42 without feeling anything. Only knew because my CGM alarmed. This is genuinely dangerous. My endo explained that the sympathetic nervous system response during arousal suppresses the typical counter-regulatory hormone response to hypoglycemia. Always wear your CGM, always have the volume up, and always respond to alarms even if the timing is terrible.",
        category: "intimacy",
        author_username: "low_awareness_psa",
        comments_count: 67,
        upvotes: 445,
        tips: ["Always wear CGM during intimacy — it could save your life", "Keep alarm volume high, don't silence for privacy", "Pre-load with 15-20g carbs if BG is below 120 before activity"],
        warnings: ["Adrenaline can mask lows down to dangerously low levels (40s)", "Severe hypo during intimacy can cause seizure — partner should know glucagon"],
        topic_tags: ["lows_during_sex", "hypo_unawareness", "cgm_during_sex", "safety"],
        sentiment: "neutral",
        confidence_score: 0.95,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      // ===== ALCOHOL (12 posts) =====
      {
        title: "The complete guide to drinking alcohol with T1D",
        content: "After 10 years of trial and error, here's my alcohol guide for T1Ds: BEER — acts like carbs first (BG goes up), then the alcohol kicks in hours later and drops you. WINE — moderate carb impact, moderate delayed low risk. SPIRITS — minimal carb impact but highest delayed hypo risk. COCKTAILS — the sugar mixers spike you, then the alcohol crashes you. The golden rule: NEVER bolus fully for alcoholic drinks. I do max 50% of what I'd normally bolus for the carbs. Set a middle-of-night alarm for 3 AM to check BG. Eat a protein-heavy snack before bed. Tell someone you're with that you're diabetic.",
        category: "alcohol",
        author_username: "responsible_t1d",
        comments_count: 134,
        upvotes: 678,
        tips: ["Never bolus more than 50% for alcoholic drinks", "Set a 3 AM alarm to check BG after drinking", "Eat protein before bed — it provides slow glucose release", "Spirits with sugar-free mixers have lowest carb impact"],
        warnings: ["Alcohol blocks liver glucose release — can cause severe delayed lows", "Drunk symptoms and low symptoms are nearly identical", "NEVER pass out without telling someone to check on you"],
        topic_tags: ["delayed_hypoglycemia", "drink_choices", "safety", "carb_management"],
        sentiment: "neutral",
        confidence_score: 0.94,
        post_type: "guide",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "College party survival guide for T1Ds",
        content: "Freshman year was a learning curve. Here's what I figured out: 1) Wear your CGM and tell at least one friend what your alarms mean. 2) Vodka soda is your best friend — zero carbs, easy to nurse. 3) NEVER go to bed drunk without eating something substantial. 4) Keep your pump on — just reduce basal by 20-30%. 5) The morning after, your liver is still processing alcohol and you WILL go low. Eat breakfast even if you feel terrible. 6) Carry a medical ID — if you pass out, you want EMTs to know it's diabetes not just alcohol. 7) Never take insulin to correct a high while drunk — the alcohol will drop you later anyway.",
        category: "alcohol",
        author_username: "college_t1d",
        comments_count: 92,
        upvotes: 534,
        tips: ["Vodka soda = zero carb alcoholic drink", "Reduce basal by 20-30% when drinking", "Always eat before sleeping after drinking", "Carry medical ID to every party"],
        warnings: ["Passing out from a low can be mistaken for being drunk", "Morning-after lows can be severe and prolonged", "Never correct a high with full dose while drinking"],
        topic_tags: ["college_life", "party_safety", "delayed_hypoglycemia", "medical_id"],
        sentiment: "positive",
        confidence_score: 0.89,
        post_type: "guide",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "I had a seizure from a low after drinking — my story",
        content: "I want to share this because it could save someone's life. I'm 23, A1C 7.2, generally well-managed. Went out with friends, had 4-5 beers over 3 hours. Bolused for the carbs like I normally would (mistake #1). Went to bed without eating (mistake #2). Didn't set an alarm (mistake #3). My roommate found me seizing at 4 AM. BG was 28. EMTs gave me glucagon and IV glucose. I was in the ER for 6 hours. This was entirely preventable. Now I follow every safety protocol religiously. Please learn from my mistake instead of making your own.",
        category: "alcohol",
        author_username: "seizure_survivor",
        comments_count: 156,
        upvotes: 823,
        tips: ["Never fully bolus for alcoholic drink carbs", "Always eat a substantial snack before bed after drinking", "Set multiple alarms for overnight BG checks", "Tell your roommate/partner about glucagon"],
        warnings: ["Alcohol + full bolus + no food = life-threatening hypo risk", "BG can drop to seizure levels (below 30) overnight", "This combination kills people — take it seriously"],
        topic_tags: ["delayed_hypoglycemia", "severe_hypo", "seizure", "safety", "personal_story"],
        sentiment: "negative",
        confidence_score: 0.96,
        post_type: "post",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Best and worst alcoholic drinks for blood sugar — ranked",
        content: "After years of CGM data while drinking, here's my personal ranking. BEST: Dry red wine (minimal spike, moderate delayed low), Vodka/gin + soda water (zero carbs), Light beer like Michelob Ultra (2.6g carbs). OKAY: Dry white wine, Whiskey neat. WORST: Regular beer (15-20g carbs + alcohol double whammy), Margaritas (pure sugar bomb), Long Island iced tea (multiple spirits + sugary mixer), Craft IPAs (can be 20+ carbs each). Pro tip: Look up carb counts before ordering. Most cocktail menus are a carb minefield. Stick with spirits + sugar-free mixers and you'll have the most predictable experience.",
        category: "alcohol",
        author_username: "cgm_bartender",
        comments_count: 87,
        upvotes: 445,
        tips: ["Dry wine and spirits with soda water are safest choices", "Look up carb counts before ordering", "Light beers have significantly fewer carbs than craft beers"],
        warnings: ["Cocktails with juice/syrup can contain 40-60g carbs each", "Craft IPAs are carb bombs — up to 25g per pint"],
        topic_tags: ["drink_choices", "carb_management", "cgm_data"],
        sentiment: "positive",
        confidence_score: 0.87,
        post_type: "guide",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Social pressure to drink with T1D — how I handle it",
        content: "The hardest part about alcohol and T1D isn't the blood sugar management — it's the social pressure. 'Come on, one more won't hurt!' Actually, it might. I've developed a few strategies: 1) Order a soda water with lime — nobody can tell it's not a cocktail. 2) Be honest with close friends about why you're limiting drinks. 3) Volunteer to be the designated driver — gives you a legitimate reason. 4) If someone won't respect your limits, that's a them problem, not a you problem. You don't owe anyone an explanation about your health decisions.",
        category: "alcohol",
        author_username: "sober_curious_t1d",
        comments_count: 64,
        upvotes: 378,
        tips: ["Soda water with lime is an undetectable non-alcoholic option", "Being the DD gives a socially accepted reason to not drink", "Real friends respect health boundaries"],
        warnings: ["Never let social pressure override your diabetes management"],
        topic_tags: ["social_pressure", "mental_health", "boundaries", "sober_strategies"],
        sentiment: "positive",
        confidence_score: 0.84,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Wine tasting with T1D — my experience at Napa Valley",
        content: "Took a wine country trip and learned some things. Each tasting pour is about 1-2 oz, so the carb impact per pour is tiny. Over a full day of 5 wineries with 5-6 tastes each, I drank the equivalent of about 3 glasses of wine. I used the spit bucket for most heavy reds (not the classiest move but my BG thanked me). Key learning: the walking between wineries and the food pairings helped stabilize my BG more than I expected. I ran about 10% lower basal and stayed 80-200 most of the day. Totally doable as a T1D experience.",
        category: "alcohol",
        author_username: "wine_t1d_tourist",
        comments_count: 28,
        upvotes: 156,
        tips: ["Tasting pours are small — carb impact is minimal per pour", "Use spit buckets to reduce actual alcohol consumption", "Walking between venues helps stabilize blood sugar"],
        warnings: ["Cumulative effect of many small pours adds up", "Wine country often means limited food options — pack snacks"],
        topic_tags: ["drink_choices", "travel", "social_events"],
        sentiment: "positive",
        confidence_score: 0.82,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Alcohol and CGM accuracy — does drinking affect sensor readings?",
        content: "I've noticed my Dexcom reads about 15-20 mg/dL higher than my actual BG when I'm drinking. Did some research and it turns out alcohol can interfere with interstitial fluid glucose readings. The lag between blood glucose and interstitial glucose gets worse when you're dehydrated (which alcohol causes). So your CGM might show 100 when you're actually at 80. This means your LOW alarm might come later than it should. My solution: I mentally subtract 15 from my CGM reading when I've been drinking and treat the low earlier.",
        category: "alcohol",
        author_username: "sensor_science",
        comments_count: 43,
        upvotes: 267,
        tips: ["Mentally subtract 15-20 from CGM readings while drinking", "Stay hydrated — dehydration worsens CGM accuracy", "Treat potential lows earlier than usual when drinking"],
        warnings: ["CGM may overread by 15-20 mg/dL during alcohol consumption", "Dehydration from alcohol increases CGM-to-BG lag time"],
        topic_tags: ["cgm_accuracy", "dehydration", "sensor_interference"],
        sentiment: "neutral",
        confidence_score: 0.86,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Keto cocktails and T1D — a surprisingly good combo",
        content: "I started doing keto to help with BG management and discovered it also makes drinking easier. Most keto-friendly cocktails (vodka soda, gin and diet tonic, whiskey) have near-zero carbs. My BG barely moves when I drink these compared to when I used to drink beer or cocktails with juice. The tradeoff: alcohol hits harder on keto because your liver is already busy with ketone production. So I get buzzed faster on fewer drinks, which is actually a benefit for diabetes management (less total alcohol = less delayed hypo risk). Just watch for ketoacidosis if you're drinking heavily — alcohol + keto + T1D can be risky.",
        category: "alcohol",
        author_username: "keto_cocktails",
        comments_count: 37,
        upvotes: 189,
        tips: ["Keto-friendly drinks minimize carb-related BG spikes", "Alcohol hits harder on keto — you need fewer drinks", "Fewer drinks = less delayed hypoglycemia risk"],
        warnings: ["Keto + alcohol + T1D increases DKA risk", "Monitor ketones when combining keto and alcohol"],
        topic_tags: ["drink_choices", "keto_diet", "carb_management", "dka_risk"],
        sentiment: "positive",
        confidence_score: 0.83,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Bartender with T1D — occupational challenges and tips",
        content: "I've been bartending for 3 years as a T1D. The challenges are unique: standing for 8+ hours affects BG, constant exposure to sugary drinks and garnishes, late nights mess with basal patterns, and taste-testing new cocktails is part of the job. My system: I wear my CGM with high-contrast display so I can check between orders. I keep juice boxes under the bar. I've trained my coworkers on glucagon. I reduce my basal by 15% on shift nights because the physical activity of bartending drops me. The biggest challenge is the post-shift beer culture — I stick to one light beer max.",
        category: "alcohol",
        author_username: "diabetic_bartender",
        comments_count: 44,
        upvotes: 213,
        tips: ["Reduce basal 15% for physically active shifts", "Keep fast-acting sugar hidden but accessible at your workstation", "Train coworkers on emergency glucagon use"],
        warnings: ["Extended standing and physical activity increases hypo risk", "Post-shift drinking culture adds to delayed hypo risk"],
        topic_tags: ["workplace", "physical_activity", "social_pressure", "basal_adjustment"],
        sentiment: "neutral",
        confidence_score: 0.84,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Hangover management for T1Ds — the morning-after protocol",
        content: "Hangover mornings are extra complicated with T1D. Your liver is still processing alcohol, so it's not releasing glucose normally. This means: 1) You're at higher risk for lows until about noon. 2) Don't skip breakfast even if nauseous — eat something even if it's crackers. 3) Reduce morning bolus by 30-50% since the alcohol is still suppressing liver glucose. 4) Hydrate like crazy — dehydration makes everything worse including CGM accuracy. 5) Don't exercise to 'sweat it out' — this dramatically increases hypo risk. 6) Check BG every hour until you feel normal again.",
        category: "alcohol",
        author_username: "hangover_protocol",
        comments_count: 51,
        upvotes: 298,
        tips: ["Eat breakfast even if nauseous — crackers or toast is enough", "Reduce morning bolus by 30-50%", "Hydrate aggressively — water and electrolytes", "Check BG hourly until you feel stable"],
        warnings: ["Don't exercise hungover — extremely high hypo risk", "Liver glucose output suppressed for 12-24 hours after heavy drinking", "Vomiting from hangover + insulin on board = dangerous low risk"],
        topic_tags: ["hangover", "morning_after", "safety", "hydration"],
        sentiment: "neutral",
        confidence_score: 0.88,
        post_type: "guide",
        source_type: "reddit",
        is_published: true,
      },
      // ===== SUBSTANCES (8 posts) =====
      {
        title: "Cannabis and T1D: What the community has learned",
        content: "Disclaimer: I'm not advocating drug use, just sharing real experiences. Cannabis affects T1Ds differently than non-diabetics. THC tends to increase appetite (munchies), which can lead to over-eating and BG spikes if you don't bolus correctly. CBD alone seems to have minimal BG impact. Edibles are trickier than smoking because the delayed onset means you might munch while waiting for it to kick in. Some users report cannabis slightly increases insulin sensitivity. The biggest risk: being too high to properly manage a low. Always have accessible glucose and a sober buddy who knows your signs.",
        category: "drug_effects",
        author_username: "honest_discussion",
        comments_count: 87,
        upvotes: 345,
        tips: ["Pre-portion snacks before consuming to avoid munchie-driven spikes", "CBD alone has minimal BG impact compared to THC", "Have glucose accessible and a sober friend who knows your signs"],
        warnings: ["Being impaired can prevent proper low treatment", "Edibles + delayed munchies = unpredictable BG roller coaster", "Cannabis can mask or mimic low symptoms"],
        topic_tags: ["cannabis", "munchies", "harm_reduction", "insulin_sensitivity"],
        sentiment: "neutral",
        confidence_score: 0.85,
        post_type: "post",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Edibles dosing with T1D — my strategy for staying in range",
        content: "I use medical cannabis edibles for chronic pain (also T1D-related neuropathy, fun combo). Here's my strategy: I eat the edible WITH a meal so I can bolus for both the food and any snacking that follows. I use low-dose edibles (5mg) so I stay functional enough to manage my diabetes. I pre-set my phone alarm for 2 hours after taking the edible — that's when munchies peak for me, and it reminds me to check BG. I have a 'munchie kit' that's pre-measured: cheese, nuts, and one small treat, all pre-bolused. This keeps me from raiding the kitchen and spiking to 350.",
        category: "drug_effects",
        author_username: "medical_cannabis_t1d",
        comments_count: 52,
        upvotes: 267,
        tips: ["Take edibles with a meal to combine bolusing", "Pre-measure a 'munchie kit' with pre-bolused snacks", "Set alarm for 2 hours post-consumption to check BG"],
        warnings: ["High-dose edibles impair ability to manage diabetes safely", "Don't drive or operate insulin pump adjustments while impaired"],
        topic_tags: ["cannabis", "edibles", "munchies", "carb_management", "neuropathy"],
        sentiment: "neutral",
        confidence_score: 0.83,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Party drugs and CGM reliability — what you need to know",
        content: "This is a harm reduction post, not endorsement. Stimulants (MDMA, cocaine, amphetamines) can cause significant BG spikes due to adrenaline and stress hormone release. Your CGM may lag behind rapid changes. MDMA specifically can cause jaw clenching which some people mistake for hypo symptoms. Stimulants also suppress appetite, meaning you might not eat for hours — risky with active insulin. Psychedelics (psilocybin, LSD) generally have less direct BG impact but can make it impossible to read your CGM or operate your pump coherently. The #1 rule: NEVER use substances alone as a T1D.",
        category: "drug_effects",
        author_username: "harm_reduction_t1d",
        comments_count: 76,
        upvotes: 312,
        tips: ["Never use substances alone — always have a sober T1D-aware buddy", "Pre-eat and reduce active insulin before potential appetite suppression", "Set multiple loud CGM alarms that don't require interaction to notice"],
        warnings: ["Stimulants cause unpredictable BG spikes from stress hormones", "Psychedelics can make you unable to read/operate medical devices", "CGM lag is amplified during rapid BG changes from stimulants"],
        topic_tags: ["harm_reduction", "stimulants", "psychedelics", "cgm_accuracy", "safety"],
        sentiment: "negative",
        confidence_score: 0.88,
        post_type: "guide",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Nicotine and T1D: Vaping, smoking, and blood sugar effects",
        content: "A lot of T1Ds don't realize nicotine affects blood sugar. Nicotine causes insulin resistance — studies show smokers need about 15-20% more insulin. When I quit vaping, my total daily insulin dropped noticeably. Vaping specifically: the PG/VG liquids are mostly inert for BG, but nicotine itself increases cortisol and adrenaline, which raises BG. Flavored vape liquids can contain trace sugars but the amount is negligible. The bigger concern: nicotine + T1D = accelerated cardiovascular damage. We're already at higher risk for heart disease. Adding nicotine to the mix is particularly risky.",
        category: "drug_effects",
        author_username: "quit_vaping_t1d",
        comments_count: 41,
        upvotes: 198,
        tips: ["Expect insulin needs to decrease 15-20% if you quit nicotine", "Track BG changes when starting or stopping nicotine products", "Nicotine gum/patches have same insulin resistance effects as vaping/smoking"],
        warnings: ["Nicotine + T1D = significantly accelerated cardiovascular risk", "Nicotine causes insulin resistance requiring higher doses"],
        topic_tags: ["nicotine", "vaping", "smoking", "insulin_resistance", "cardiovascular"],
        sentiment: "negative",
        confidence_score: 0.87,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Festival season survival guide for T1Ds",
        content: "I go to 3-4 music festivals a year as a T1D. Lessons learned the hard way: 1) Bring 3x the supplies you think you need — heat kills insulin and sensors. 2) Keep insulin in an insulated bag with ice packs (Frio works great). 3) Dehydration from dancing + heat can spike BG dramatically. 4) If you choose to drink or use substances, TELL your festival buddies about your diabetes and where your glucagon is. 5) Medical tents at festivals know about diabetes — don't hesitate to use them. 6) Bring a letter from your endo for security explaining your devices and supplies.",
        category: "drug_effects",
        author_username: "festival_t1d",
        comments_count: 55,
        upvotes: 287,
        tips: ["Pack 3x supplies — heat destroys insulin and sensors", "Frio cooling cases keep insulin safe without refrigeration", "Get a doctor's letter for security about your devices/supplies"],
        warnings: ["Heat above 86°F (30°C) degrades insulin within hours", "Dehydration from heat + activity causes severe BG spikes", "Festival medical tents may not have T1D-specific knowledge"],
        topic_tags: ["festivals", "heat_management", "harm_reduction", "travel", "supply_management"],
        sentiment: "positive",
        confidence_score: 0.86,
        post_type: "guide",
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Caffeine and blood sugar: The underrated substance interaction",
        content: "Nobody talks about caffeine as a 'substance' but for T1Ds it's significant. My morning coffee spikes me 40-60 mg/dL even without milk or sugar. Caffeine stimulates cortisol and adrenaline release, which triggers liver glucose dump. Energy drinks are even worse — the caffeine + taurine + often sugar combo can be a BG nightmare. Pre-workout supplements are basically concentrated caffeine + stimulants. I now bolus 1 unit for my black coffee and it works perfectly. Took me 2 years of mysterious morning spikes before I figured this out.",
        category: "drug_effects",
        author_username: "caffeine_bolus",
        comments_count: 93,
        upvotes: 456,
        tips: ["Bolus 0.5-1 unit for black coffee based on personal testing", "Energy drinks combine caffeine spike + sugar spike — double whammy", "Test caffeine's effect on YOUR BG — it varies person to person"],
        warnings: ["Pre-workout supplements can spike BG 80-120 mg/dL", "Caffeine effects stack with stress hormones in the morning"],
        topic_tags: ["caffeine", "coffee", "energy_drinks", "morning_spikes", "cortisol"],
        sentiment: "neutral",
        confidence_score: 0.9,
        post_type: "post",
        is_featured: false,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Harm reduction: General principles for T1Ds using substances",
        content: "As a T1D harm reduction advocate, here are universal principles regardless of what substance: 1) NEVER use alone. Always have someone who knows about your diabetes. 2) Eat something before and keep glucose accessible. 3) Keep your CGM on and alarm volume up. 4) Don't adjust pump settings while impaired — set them before. 5) Reduce active insulin if you'll be physically active (dancing, etc). 6) Carry medical ID. 7) Know your local emergency number. 8) If in doubt, treat for a low rather than risking it. 9) Don't mix multiple substances — it makes BG prediction impossible. 10) Your health comes first. Always.",
        category: "drug_effects",
        author_username: "t1d_harm_reduction",
        comments_count: 68,
        upvotes: 389,
        tips: ["Pre-set pump adjustments before any impairment", "Always carry medical ID and glucose", "Treat for a low if in doubt — sugar won't kill you, a severe low can"],
        warnings: ["Mixing substances makes blood sugar completely unpredictable", "Impairment reduces ability to recognize and treat lows", "Emergency responders need to know about your diabetes"],
        topic_tags: ["harm_reduction", "safety", "general_principles", "medical_id"],
        sentiment: "neutral",
        confidence_score: 0.92,
        post_type: "guide",
        is_featured: true,
        source_type: "reddit",
        is_published: true,
      },
      {
        title: "Psychedelics and T1D management: A candid discussion",
        content: "I want to share my experience with psilocybin and T1D for harm reduction purposes. The direct BG impact was minimal — mushrooms didn't spike or crash me. But the challenge was cognitive: at the peak, I couldn't read my CGM graph properly. Colors were distracting, numbers were hard to process. I set my pump to a temp basal of -20% before the experience and ate a steady snack (cheese and crackers, pre-bolused). My trip sitter was briefed on my diabetes and had glucose tabs ready. It went fine, but I was acutely aware of how vulnerable I'd be if something went wrong. Not recommending, just being honest.",
        category: "drug_effects",
        author_username: "candid_t1d",
        comments_count: 49,
        upvotes: 178,
        tips: ["Set temp basal BEFORE onset of effects", "Have a fully briefed, sober trip sitter", "Pre-eat and pre-bolus to reduce need for decisions during experience"],
        warnings: ["Cognitive impairment makes device operation extremely difficult", "Cannot reliably read CGM data or calculate insulin doses while impaired", "Have glucagon accessible and trip sitter trained on its use"],
        topic_tags: ["psychedelics", "psilocybin", "harm_reduction", "trip_sitter", "safety"],
        sentiment: "neutral",
        confidence_score: 0.8,
        post_type: "post",
        source_type: "reddit",
        is_published: true,
      },
      // ===== RESEARCH & ARTICLES (8 posts) =====
      {
        title: "Diabeloop Study: Significant Sex Differences in Insulin Requirements for T1D",
        content: "A major study by Diabeloop analyzed insulin delivery data from their DBLG1 closed-loop system and revealed significant differences between male and female T1D patients. Key findings: Women require on average 15-20% less total daily insulin than men of similar weight. Women show greater insulin sensitivity variation across menstrual cycles, with up to 30% more insulin needed in the luteal phase. The automated system performed differently based on sex, suggesting that closed-loop algorithms should incorporate sex-based adjustments. This has direct implications for intimate health, as hormonal fluctuations affect both insulin needs and sexual experiences.",
        category: "intimacy",
        source_url: "https://www.diabeloop.com/news/company/diabeloop-study-reveals-significative-sex-differences-in-insulin-requirements-for-type-1-diabetes-patients",
        source_platform: "Diabeloop",
        author_username: "Diabeloop Research",
        comments_count: 12,
        upvotes: 189,
        tips: ["Women should track menstrual cycle alongside insulin doses", "Closed-loop systems may need sex-specific tuning", "Discuss sex-based dosing adjustments with your endocrinologist"],
        warnings: ["One-size-fits-all insulin algorithms may underperform for women"],
        topic_tags: ["sex_differences", "insulin_requirements", "closed_loop", "hormonal_effects", "clinical_research"],
        sentiment: "neutral",
        confidence_score: 0.95,
        post_type: "research",
        is_featured: true,
        source_type: "research",
        is_published: true,
      },
      {
        title: "EUROSPEC Study: Sex Differences in Insulin Requirements — Research Poster",
        content: "Presented at the European Society for Paediatric Endocrinology, this research poster examines sex-based differences in insulin requirements among Type 1 diabetes patients. The study analyzed data from multiple clinical sites across Europe and found that biological sex significantly influences basal insulin requirements, bolus ratios, and overall glycemic variability. Female patients showed higher glycemic variability correlating with menstrual cycle phases, while male patients showed more stable but generally higher total insulin needs. The findings support the need for sex-specific treatment protocols and algorithm adjustments in automated insulin delivery systems.",
        category: "intimacy",
        source_url: "https://abstracts.eurospe.org/hrp/0086/eposters/hrp0086rfc5.3_eposter.pdf",
        source_platform: "ESPE",
        author_username: "ESPE Research",
        comments_count: 5,
        upvotes: 78,
        tips: ["Research supports personalized insulin dosing based on biological sex", "Track glycemic variability over menstrual cycle for better patterns"],
        warnings: ["Current pump algorithms may not account for sex-based differences"],
        topic_tags: ["sex_differences", "insulin_requirements", "clinical_research", "glycemic_variability"],
        sentiment: "neutral",
        confidence_score: 0.97,
        post_type: "research",
        is_featured: true,
        source_type: "research",
        is_published: true,
      },
      {
        title: "GrownUpT1Ds: A Community for Adult-Diagnosed Type 1 Diabetics",
        content: "GrownUpT1Ds.org is a community and resource hub specifically for adults living with Type 1 diabetes. Unlike most T1D resources that focus on pediatric diagnosis, GrownUpT1Ds addresses the unique challenges of managing T1D as an adult — including navigating intimacy, alcohol in social settings, workplace challenges, and the emotional burden of a chronic disease in adulthood. The community provides peer support, educational resources, and a judgment-free space for discussing the 'grown-up' aspects of T1D that are often overlooked by traditional diabetes education programs. They're particularly strong on topics like sexual health, alcohol management, and mental health.",
        category: "intimacy",
        source_url: "https://grownupt1ds.org/about-diabetes-type-1-support-community/",
        source_platform: "GrownUpT1Ds",
        author_username: "GrownUpT1Ds",
        comments_count: 23,
        upvotes: 234,
        tips: ["GrownUpT1Ds offers free resources for adult-specific T1D challenges", "Their community forums cover intimacy, alcohol, and mental health openly", "Great resource for adult-diagnosed T1Ds who feel out of place in pediatric-focused groups"],
        warnings: [],
        topic_tags: ["community_resource", "adult_diagnosis", "sexual_health", "mental_health"],
        sentiment: "positive",
        confidence_score: 0.9,
        post_type: "article",
        is_featured: true,
        source_type: "organization",
        is_published: true,
      },
      {
        title: "Sexual Dysfunction in Type 1 Diabetes: A Systematic Review",
        content: "A comprehensive review of literature on sexual dysfunction in T1D reveals that up to 35% of men with T1D experience some form of erectile dysfunction, with prevalence increasing with diabetes duration and poor glycemic control. For women, up to 40% report sexual dysfunction including decreased arousal, pain, and difficulty with orgasm. Key risk factors include: A1C consistently above 8%, diabetes duration over 10 years, presence of other complications (neuropathy, retinopathy), and depression/anxiety. Importantly, the review found that improved glycemic control (A1C reduction of 1% or more) was associated with significant improvement in sexual function for both genders.",
        category: "intimacy",
        author_username: "Medical Review",
        comments_count: 18,
        upvotes: 156,
        tips: ["A1C reduction of 1%+ significantly improves sexual function", "Regular screening for sexual dysfunction should be part of T1D care", "Depression treatment alongside diabetes management improves outcomes"],
        warnings: ["35% of men and 40% of women with T1D report some sexual dysfunction", "Risk increases with diabetes duration and poor control"],
        topic_tags: ["erectile_dysfunction", "sexual_dysfunction", "clinical_research", "a1c_impact"],
        sentiment: "neutral",
        confidence_score: 0.96,
        post_type: "research",
        is_featured: false,
        source_type: "research",
        is_published: true,
      },
      {
        title: "Impact of Alcohol on Type 1 Diabetes Management: Clinical Guidelines Review",
        content: "Current clinical guidelines on alcohol and T1D management are summarized from ADA, JDRF, and endocrine society publications. Key recommendations: Limit consumption to 1 drink/day for women, 2 for men. Never drink on an empty stomach. Monitor blood glucose before, during, and up to 24 hours after drinking. The risk of delayed hypoglycemia is highest 6-12 hours after drinking. Glucagon may be less effective during alcohol-induced hypoglycemia because the liver is busy metabolizing alcohol. Patients should be educated on the difference between intoxication symptoms and hypoglycemia symptoms, as they can be nearly identical.",
        category: "alcohol",
        author_username: "Clinical Guidelines Review",
        comments_count: 8,
        upvotes: 123,
        tips: ["Monitor BG for up to 24 hours after drinking", "Glucagon effectiveness is reduced during alcohol metabolism", "Educate companions on distinguishing drunk vs. low symptoms"],
        warnings: ["Delayed hypo risk peaks 6-12 hours after drinking", "Glucagon may not work normally when liver is processing alcohol"],
        topic_tags: ["clinical_guidelines", "delayed_hypoglycemia", "glucagon", "safety"],
        sentiment: "neutral",
        confidence_score: 0.97,
        post_type: "research",
        is_featured: false,
        source_type: "research",
        is_published: true,
      },
      {
        title: "Cannabis and Blood Glucose: What the Research Actually Says",
        content: "A review of current research on cannabis use among T1D patients reveals mixed findings. Some studies suggest cannabinoids may have anti-inflammatory properties that could benefit beta cell preservation in early T1D. However, practical concerns dominate: THC increases appetite leading to carbohydrate consumption, cannabis use is associated with higher rates of DKA in observational studies (possibly due to impaired self-management rather than direct effect), and cannabis hyperemesis syndrome can mimic DKA symptoms, leading to delayed treatment. CBD-only products show no significant direct BG impact in limited studies. The research is still early-stage and no clinical guidelines exist specifically for T1D patients using cannabis.",
        category: "drug_effects",
        author_username: "Research Digest",
        comments_count: 15,
        upvotes: 167,
        tips: ["CBD-only products appear to have minimal direct BG impact", "Some research suggests anti-inflammatory benefits of cannabinoids", "More research is needed — no official clinical guidelines exist yet"],
        warnings: ["Cannabis use associated with higher DKA rates in T1D populations", "Cannabis hyperemesis syndrome can mimic DKA — dangerous misdiagnosis risk", "THC-induced appetite increases lead to carbohydrate over-consumption"],
        topic_tags: ["cannabis", "clinical_research", "dka_risk", "cbd"],
        sentiment: "neutral",
        confidence_score: 0.91,
        post_type: "research",
        is_featured: false,
        source_type: "research",
        is_published: true,
      },
      {
        title: "The Psychology of Disclosure: Telling Partners About Chronic Illness",
        content: "Research from health psychology journals explores optimal strategies for disclosing chronic conditions like T1D to romantic and sexual partners. Studies found that: 1) Earlier disclosure (before physical intimacy) is associated with better relationship outcomes. 2) Partners who were told in a casual, matter-of-fact way reported less anxiety than those who received a 'serious sit-down' disclosure. 3) Providing practical information (what the devices do, what the alarms mean) reduces partner anxiety more than medical detail. 4) Couples who integrate diabetes management as a team activity report higher relationship satisfaction. 5) Fear of rejection is the biggest barrier to disclosure, but actual rejection rates are very low (under 5% in studies).",
        category: "intimacy",
        author_username: "Health Psychology Review",
        comments_count: 22,
        upvotes: 198,
        tips: ["Casual, matter-of-fact disclosure produces best outcomes", "Focus on practical info (devices, alarms) not medical complexity", "Rejection rate is under 5% — fear is worse than reality"],
        warnings: ["Delaying disclosure increases anxiety for both partners"],
        topic_tags: ["disclosure_to_partners", "psychology", "clinical_research", "relationships"],
        sentiment: "positive",
        confidence_score: 0.93,
        post_type: "research",
        is_featured: false,
        source_type: "research",
        is_published: true,
      },
      {
        title: "Neuropathy and Sexual Health in T1D: Prevention and Treatment Options",
        content: "Diabetic neuropathy is one of the most common complications affecting sexual health in T1D patients. Peripheral neuropathy can reduce genital sensation, while autonomic neuropathy can affect arousal, lubrication, erection, and orgasm. Prevention is primarily through tight glycemic control — research shows that maintaining A1C below 7% reduces neuropathy risk by 60-70%. For existing neuropathy: medications like duloxetine and pregabalin can help with nerve pain. PDE5 inhibitors (Viagra, Cialis) remain first-line for ED. For women, topical estrogen and lubricants address vaginal dryness. Emerging treatments include nerve growth factor therapies and stem cell approaches currently in clinical trials.",
        category: "intimacy",
        author_username: "Neuropathy Research",
        comments_count: 14,
        upvotes: 145,
        tips: ["A1C below 7% reduces neuropathy risk by 60-70%", "PDE5 inhibitors are effective for diabetes-related ED", "Topical treatments available for vaginal dryness from neuropathy"],
        warnings: ["Neuropathy damage is often irreversible — prevention through good control is key", "Both peripheral and autonomic neuropathy affect sexual function"],
        topic_tags: ["neuropathy", "sexual_dysfunction", "prevention", "treatment_options", "clinical_research"],
        sentiment: "neutral",
        confidence_score: 0.95,
        post_type: "research",
        is_featured: false,
        source_type: "research",
        is_published: true,
      },
    ];

    // Insert all posts
    const { data: insertedPosts, error } = await supabase
      .from("adult_content_posts")
      .insert(posts)
      .select("id, title");

    if (error) {
      console.error("Insert error:", error);
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Clear existing comments
    await supabase.from("adult_content_comments").delete().neq("id", "00000000-0000-0000-0000-000000000000");

    // Seed comments for each post
    const commentPool = [
      { author: "t1d_warrior_23", content: "This is exactly my experience — I run a temp basal of -20% before dates and it works perfectly. Took me years to figure this out.", score: 127 },
      { author: "dx_at_five", content: "My endo literally never mentioned this. Thank you for sharing. I'm bringing this up at my next appointment.", score: 98 },
      { author: "pump_life_2019", content: "I've been T1D for 18 years and this is the first time I've seen someone articulate what I've been feeling. You're not alone.", score: 145 },
      { author: "looping_queen", content: "The closed-loop system changed everything for me in these situations. Before that I was constantly anxious about lows.", score: 89 },
      { author: "cgm_convert", content: "Switched my sensor to back of arm after reading a similar post. Game changer. Zero issues since.", score: 112 },
      { author: "newly_diagnosed_22", content: "I was just diagnosed 6 months ago and this is SO helpful. Nobody talks about this stuff in the hospital.", score: 76 },
      { author: "endo_nurse_t1d", content: "As a nurse with T1D, I can confirm everything here. We need more open discussions like this in clinical settings.", score: 134 },
      { author: "partner_of_t1d", content: "I'm the partner of someone with T1D. This thread helped me understand so much. Thank you all for being so open.", score: 156 },
      { author: "teen_diabetic", content: "I'm 17 and terrified about all of this. Reading that it's manageable makes me feel a lot better.", score: 67 },
      { author: "a1c_warrior", content: "Got my A1C from 9.2 to 6.4 and the difference is night and day. Everything this post says about control is true.", score: 103 },
      { author: "camp_counselor_t1d", content: "I work at a diabetes camp and we're starting to address these topics for older teens. Posts like this help us know what to cover.", score: 88 },
      { author: "dexcom_devotee", content: "My Dexcom has alarmed at the worst possible moments 😂 but honestly it's kept me safe. Worth the awkwardness.", score: 94 },
      { author: "insulin_rebel", content: "I used to hide my pump from partners. Now I show it off. The confidence shift was everything.", score: 121 },
      { author: "low_fighter", content: "Post-activity lows hit me HARD about 45 min after. I always keep Skittles on the nightstand now. Pro tip.", score: 78 },
      { author: "type_one_mom", content: "As a mom with T1D, the pregnancy section resonates so much. First trimester lows were terrifying.", score: 91 },
      { author: "research_nerd_t1d", content: "The Diabeloop study findings align with what I've experienced. Great to see actual data backing community knowledge.", score: 65 },
      { author: "dating_app_diabetic", content: "I put 'Type 1 Diabetic' in my dating profile now. Filters out anyone who'd be weird about it. Saves time.", score: 143 },
      { author: "omnipod_user_99", content: "Omnipod on the arm is the way to go. Had it on my stomach once and it got knocked off. Expensive lesson.", score: 82 },
      { author: "midnight_snacker", content: "The delayed low thing is SO real. I've woken up at 3am drenched in sweat after an active evening. Always eat carbs after.", score: 97 },
      { author: "libre_fan", content: "Libre 3 is small enough that most people don't even notice it. Game changer for body confidence.", score: 71 },
      { author: "diabetes_therapist", content: "I'm a therapist specializing in chronic illness. The mental health aspect of this is hugely underaddressed. Great discussion.", score: 108 },
      { author: "college_t1d", content: "Freshman year was rough trying to figure all this out. Wish I had found this community sooner.", score: 59 },
      { author: "honeymoon_phase", content: "Still in my honeymoon phase so things are unpredictable. This gives me hope that it gets more manageable.", score: 44 },
      { author: "thirty_year_veteran", content: "30 years with T1D. The technology now vs. when I was diagnosed is incredible. These conversations wouldn't have happened back then.", score: 132 },
      { author: "basal_tweaker", content: "I have 6 different basal profiles for different situations. It sounds extreme but it works. Your body, your rules.", score: 85 },
      { author: "juice_box_hero", content: "My partner calls the nightstand juice boxes our 'emergency kit.' They're incredibly supportive. Communication is key.", score: 116 },
      { author: "sensor_warrior", content: "SkinTac + Tegaderm combo has saved me hundreds of dollars in lost sensors. Can't recommend enough.", score: 73 },
      { author: "endo_appointment_tips", content: "Print this thread and bring it to your endo. Seriously. They need to hear what patients actually deal with.", score: 99 },
      { author: "night_owl_diabetic", content: "The adrenaline masking lows thing is real and scary. I always set a CGM alarm for 80 now instead of the default 70.", score: 87 },
      { author: "gluten_free_t1d", content: "Dealing with celiac + T1D + all of this is next level. But we manage. One day at a time.", score: 54 },
    ];

    const allComments: Array<{ post_id: string; author_anonymous: string; content: string; score: number }> = [];

    if (insertedPosts) {
      for (const post of insertedPosts) {
        // 8-15 comments per post
        const numComments = 8 + Math.floor(Math.random() * 8);
        const shuffled = [...commentPool].sort(() => Math.random() - 0.5);
        for (let i = 0; i < numComments && i < shuffled.length; i++) {
          allComments.push({
            post_id: post.id,
            author_anonymous: shuffled[i].author,
            content: shuffled[i].content,
            score: shuffled[i].score + Math.floor(Math.random() * 20) - 10,
          });
        }
      }
    }

    let commentsInserted = 0;
    if (allComments.length > 0) {
      // Insert in batches of 100
      for (let i = 0; i < allComments.length; i += 100) {
        const batch = allComments.slice(i, i + 100);
        const { error: commentError } = await supabase.from("adult_content_comments").insert(batch);
        if (commentError) {
          console.error("Comment insert error:", commentError);
        } else {
          commentsInserted += batch.length;
        }
      }
    }

    return new Response(
      JSON.stringify({ success: true, postsInserted: posts.length, commentsInserted }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    console.error("Error:", err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
